### ISSUE TITLE
Debug Assert: map/set iterators incompatible

### ISSUE THREAD

**Issue by hypernewbie** [cginternals/glbinding#101]
Visual Studio 2013, on glbindingd.dll>	

glbindingd.dll!glbinding::`dynamic initializer for 'Meta_FunctionStringsByExtension''() Line 281	C++

hits an assert.

**Comment by scheibel** [comment]
Can you refine your used system?
Which Windows do you work with? What update of Visual Studio? Did you enable OPTION_GL_BY_STRINGS?

And also important: What is the assertion that failed?

**Comment by rlux** [comment]
This is a compiler bug and happens when you did not install Visual Studio 2013 **Update 3**.
