### ISSUE TITLE
Support for typically used signatures that are missing

### ISSUE THREAD

**Issue by scheibel** [cginternals/glbinding#108]
Patch the ```gl.xml``` to support the following list of signatures:
* ```glTexParametere (glTexParameteri)```
* ```glUniform*e* (glUniform*i*)```
* ```glProgramUniform*e* (glProgramUniform*i*)```
* ```glGet*e* (glGet*i*)```
 * ```glGetFramebufferAttachmentParameterev (glGetFramebufferAttachmentParameteriv)```
* ```glGet*b* (glGet*i*)```
* ```glGetEnum (glGetInteger)```

**Comment by cgcostume** [comment]
not via patch in code generation but as additional functions header (should work for now, until templated code generation works for v2.1)

**Comment by cgcostume** [comment]
Leave as is, but prefer overloading and include patches by default.
