### ISSUE TITLE
Consider providing standalone |= operator for bitfields ?

### ISSUE THREAD

**Issue by nemerle** [cginternals/glbinding#109]
use case :
```cpp
    ClearBufferMask glFlags=GL_NONE_BIT;
    if (flags & CLEAR_COLOR)
    {
        glFlags |= GL_COLOR_BUFFER_BIT;
    }
```

**Comment by scheibel** [comment]
Does PR https://github.com/hpicgs/glbinding/pull/110 work for you?

**Comment by nemerle** [comment]
Thank You
I'll test it in ~6h. ( But looking at the patch, it looks good :) )

**Comment by nemerle** [comment]
Code in the operation_assignments_for_bitfields branch works correctly for the use case I've mentioned and as a bonus makes the code much cleaner.

Thank You :smile:
