### ISSUE TITLE
pack-glbinding.cmake uses CMAKE_SOURCE_DIR

### ISSUE THREAD

**Issue by wobakj** [cginternals/glbinding#113]
Hello,
I'm trying to create a small cross-platform OpenGL framework and would like to use glbindings for it.
When I added glbindings as submodule creating the buildfiles was only successfull when having "LICENSE" and "README.md" in my project root directory. I noticed that "pack-glbinding.cmake" uses the "CMAKE_SOURCE_DIR" variable as path to these two files.
From what I read CPack is for creating installers, is it intentional that the root directories license and readme is used when building the package?

**Comment by sbusch42** [comment]
CMake projects are not supposed to be nested like that. There is nothing wrong with including glbinding as a git-submodule into your own repository, but do not just use add_subdirectory to include it into your own build system. While we could work around that to support this kind of usage, that would mean to adapt and restrict our cmake code to an AFAIK unintended usage of cmake, and I would hate to do that. There is a construct in cmake for exactly this kind of use case: [ExternalProject](http://www.cmake.org/cmake/help/v3.0/module/ExternalProject.html). Please use that to include and build external projects within your own project.

**Comment by wobakj** [comment]
Alright, thank you for the advice!
