### ISSUE TITLE
noexcept support in Visual Studio 2015

### ISSUE THREAD

**Issue by j-o** [cginternals/glbinding#115]
Since Visual Studio 2015 supports the `noexcept` specifier, the definition of the `NOEXCEPT` macro should be adjusted accordingly (`#   if defined(_MSC_VER) && _MSC_VER < 1900`) or removed entirely, as it is not actually used anywhere. Same goes for all cmake-init based libraries.

**Comment by scheibel** [comment]
```NOEXCEPT``` in fact isn't used in our public libraries but in our internal ones that are build upon cmake-init, too.

**Comment by scheibel** [comment]
This will be covered while porting the project structure to cmake-init 2.0.
