### ISSUE TITLE
[question] Error on OS X due to OpenGL version?

### ISSUE THREAD

**Issue by ThePixelPony** [cginternals/glbinding#116]
I am using this with GLFW and the following error is produced when the headers are included:

http://pastebin.com/uPL6LvXD

I believe that it is due to OS X only supporting up to OpenGL version 3.2. Is there a way to switch to this version with glbinding?

**Comment by cgcostume** [comment]
which gcc version do you currently use? 

```ISO C++ forbids forward references to 'enum' types```

Seems that forward declerations of enum classes is not supported in you gcc yet. 
C++11 is required at least.

**Comment by ThePixelPony** [comment]
>bash-3.2# gcc --version
>Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include->dir=/usr/include/c++/4.2.1
>Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
>Target: x86_64-apple-darwin14.1.0
>Thread model: posix

It appears that I have GCC 4.2.1.
How would I go about updating?
