### ISSUE TITLE
GLextension's are shifted by 1

### ISSUE THREAD

**Issue by tly000** [cginternals/glbinding#117]
The following program code outputs `GL_ARB_base_instance` on my pc.
```c++
cout << GLextension::GL_ARB_bindless_texture << '\n';
```

This is exactly the extension before `GL_ARB_bindless_texture` in the enum.
If I want to check for an extension, I therefor have to use the following trick:
`ContextInfo::extensions().count(GLextension(extension+1))`

I use gcc 5.1 on Ubuntu 14

**Comment by scheibel** [comment]
After having a look at the according ```unorderd_map```s containing the lookup of ```GLextensions``` and their names as strings, I found them to be correct. (```Meta_ExtensionsByString.cpp``` and ```Meta_StringsByExtension.cpp```).
Even the lookup code in the map for ```GLextension``` to string conversion is the most basic version and is not likely to contain an error (see ```Meta.cpp```, ```Meta::getString(const GLextension)```).

I try to reproduce your error on my system (gcc 4.9.2, Ubuntu 15.04) and report later on.

**Comment by scheibel** [comment]
On my system your test code runs as expected.
As long as all other platforms and compilers perform as expected, I can't think of any fix for your system.

Can you create a test case outside of glbinding checking if unordered maps behave correct on your system?

**Comment by tly000** [comment]
I think the problem is a bug in gcc, that ignored that your `GLextension` enum class starts with -1. The values make perfect sense, if the enum class would start with value 0. Maybe that happened because the enum class is forward declarated inside the `types.h` header. This is of course not your code problem, but a compiler bug. Unfortunately I cant reproduce this error on any other system...

**Comment by cgcostume** [comment]
closing for now, but we will observe this for subsequent gcc revisions
