### ISSUE TITLE
Why is a static_cast<int> needed for some enums?

### ISSUE THREAD

**Issue by rggjan** [cginternals/glbinding#119]
Why is in this line:

     glTexImage2D(GL_TEXTURE_2D, 0, static_cast<int>(GL_RGB8), 64, 16, 0, GL_RGB, GL_UNSIGNED_BYTE, patches.data());

(https://github.com/cginternals/glbinding/blob/master/source/examples/cubescape/CubeScape.cpp#L120)

A static_cast from GL_RGB8 to int needed? This is not very intuitive, and makes it necessary to rewrite code to use it with glbinding...

**Comment by scheibel** [comment]
This is related to https://github.com/cginternals/glbinding/issues/107.
The main problem is, that the OpenGL API doesn't differ between ```GL(u)int``` and ```GLenum```, but glbinding does. So comes that some function signatures of the OpenGL API expects a ```GL(u)int``` where only ```GLenums``` are passed, but sometimes it is even trickier when a signature is used with mixed parameters (as in https://github.com/cginternals/glbinding/issues/107) and so, two seperated functions should be provided (one with suffix ```(u)i``` and one with suffix ```e```).

I hope this answers your question.

Of course, a solution could be for glbinding to treat ```GL(u)int``` and ```GLenum``` as equal types, but this is something we currently don't want to do.

**Comment by rggjan** [comment]
Couldn't you also just provide two overloaded functions with the same name, one taking a GLuint as third parameter and one taking a GLenum?

**Comment by cgcostume** [comment]
@rggjan yes - this would be good. But we cannot automatically figure out which gl functions are affected by that. long-term: we could extent our patching for it and manually add the functions found by users/us. BUT: glbinding is intended to be automatically generated and thus, should not deviate (too much) from the API spec which has some known flaws that we hope will be resolved in future spec updates.

**Comment by cgcostume** [comment]
Note: the spec says:

```
<param group="TextureComponentCount"><ptype>GLint</ptype> <name>internalformat</name></param>
```

I'm not quite sure why the Khronos Group decided to use ```GLint``` here - if we patch this the cast would only be required when using values not covered by the enum. We will (re)discuss and probably patch this in a few days/weeks when the parsing is refactored (not so for #107).

**Comment by rggjan** [comment]
@cgcostume I see, that makes a lot of sense. Thanks for the explanation.

**Comment by scheibel** [comment]
This issue is also covered in #108.
