### ISSUE TITLE
Function pointers and constants without gl / GL_ prefixes ?

### ISSUE THREAD

**Issue by JPGygax68** [cginternals/glbinding#121]
Given that glbinding has all its definitions in namespaces, is it really necessary to leave the traditional prefixes in the names?

The official [OpenGL reference card](https://www.khronos.org/files/opengl43-quick-reference-card.pdf) uses non-prefixed names. 

The prefixes make perfect sense when working with C of course, but it would be great if C++ users were given the choice between the prefixes and the namespaces.

**Comment by cgcostume** [comment]
Thanks for the advice - we internally discussed this some time ago. We will (re)discuss this as soon as possible. afaik we decided against this to allow the use of ```using namespace gl45``` etc. to be compliant with existing (non-glbinding) code. But getting rid of the prefixes in types and functions is intriguing: To enable both ways we could generate additional c-namespaces, e.g., ```cgl``` (in contrast to the c++ non-prefix ```gl```).

**Comment by rlux** [comment]
Another reason against it were constant names like GL_2D, GL_3D, GL_2_BYTES, etc. Without the "GL_" prefix, they would start with a number, which is not a valid C++ identifier. Other thoughts were whether the functions should then start with a lower or upper case character.

**Comment by cgcostume** [comment]
Similar thoughts here. We are currently revisiting the the python parser with respect to (1) switching to a template system and (2) preparing for gles and other khronos specifications. With this we also introduce more customization on the binding generation - Due to this discussion, we are going to provide an option to generate functions without prefixes (thanks @JPGygax68 for the request). 

However, the default glbinding will be unaffected by this - but users can customize their binding if required (blacklisting, whitelisting, specific features, prefixes, customized namespaces, ...).

(Remark: @rlux concerning these, we thought about using strings, e.g., ```TWOD``` ... :smiley:, and to avoid macro issues, we also thought about undefing every enum, e.g., ```GL_TRUE``` would become ```TRUE```...)

**Comment by JPGygax68** [comment]
On 20.10.2015 14:51, Roland Lux wrote:
>
> Another reason against it were constant names like GL_2D, GL_3D, 
> GL_2_BYTES, etc. Without the "GL_" prefix, they would start with a 
> number, which is not a valid C++ identifier. Other thoughts were 
> whether the functions should then start with a lower or upper case 
> character.
>
I didn't know, or had forgotten about those :-) Well I can't think of a 
better way than to replace them with "TWO_" and "THREE_" ...

As for case, that's a bit difficult ... The reference card uses upper 
case, but I can't think of a C++ library that does so for function 
names. Upper case seems to be reserved for class names, and going 
against that would meet with resistance for sure. On the other hand, 
there are no classes or even structs in the OpenGL API, so an exception 
could be made in this case.

On the whole though, I'd go with lower case.

**Comment by JPGygax68** [comment]
On 20.10.2015 15:04, Daniel Limberger wrote:
>
> Similar thoughts here. We are currently revisiting the the python 
> parser with respect to (1) switching to a template system and (2) 
> preparing for gles and other khronos specifications.
>
Do you have something in the pipeline for Vulkan? That would be sweet :-)
>
> With this we also introduce more customization on the binding 
> generation - Due to this discussion, we are going to provide an option 
> to generate functions without prefixes (thanks @JPGygax68 
> <https://github.com/JPGygax68> for the request).
>
> However, the default glbinding will be unaffected by this - but users 
> can customize their binding if required (blacklisting, whitelisting, 
> specific features, prefixes, customized namespaces, ...).
>
Thanks for taking this into consideration!

I would however advise against making it the users' job to generate 
their own version of the bindings, except for very special cases. Since 
this is all generated and essentially header-only code (out of the top 
of my head, sorry if I'm wrong),  you could provide multiple versions 
without adverse effects, as long as each version is clearly identified 
by its include path. Though that might a bit tricky.
>
> (Remark: @rlux <https://github.com/rlux> concerning these, we thought 
> about using strings, e.g., |TWOD| ... :smiley:, and to avoid macro 
> issues, we also thought about undefing every enum, e.g., |GL_TRUE| 
> would become |TRUE|...)
>
The TRUE and FALSE macros in Windows are nuisances. Perhaps, if GL_TRUE 
has the same value as Windows' TRUE (not sure right now), this could be 
detected and the definition of the enum then simply emitted. Could still 
cause problems though.
