### ISSUE TITLE
[Question] glTexture2D GLint internalFormat

### ISSUE THREAD

**Issue by ThePixelPony** [cginternals/glbinding#125]
How would one get the value for an RGB or RGBA internal format to supply to this function?

GL_RGBA is an enum, as opposed to an int.

**Comment by Armada651** [comment]
Just cast the enum to an int?

**Comment by ThePixelPony** [comment]
Oh, thank you. I didn't realise that one could do that.

**Comment by scheibel** [comment]
I want to add that this is a design issue of the interplay of glbinding and the OpenGL API. The current discussion can be see here: https://github.com/cginternals/glbinding/issues/119
