### ISSUE TITLE
Output operators for glEnum should be in gl namespace

### ISSUE THREAD

**Issue by rggjan** [cginternals/glbinding#126]
This code does not work with glbinding:

```c++
#include <fstream>

#include <glbinding/gl/types.h>

// Removing this namespace (keeping the content) makes it work
namespace bar {

template <class Type>
struct Point {
};

// Removing this function makes it work
template <class Type>
std::ostream& operator<< (std::ostream& stream, const Point<Type> &point);

void foo() {
  gl::GLenum test;
  std::ofstream stream;
  stream << test;
}

}
```

The error is:
> error C2679: binary '<<' : no operator found which takes a right-hand operand of type 'gl::GLenum' (or there is no acceptable conversion)

Asking on stackoverflow, the problem is that the output operator of y`gl::GLenum` in the `types.h` header should be in the `gl` namespace (`baz` is `gl` and `Bar` is `GLenum`):
http://stackoverflow.com/questions/34198039/c-output-stream-not-working-with-templates-and-namespaces/34198322#34198322

**Comment by scheibel** [comment]
Thanks for reporting.
