### ISSUE TITLE
Add support for glx.xml and wgl.xml

### ISSUE THREAD

**Issue by hf6b** [cginternals/glbinding#132]
glbinding should generate APIs for all wgl\* and glX\* functions as well from wgl.xml and glx.xml.

Currently glbinding only generates code from gl.xml. This leaves out a lot of extensions that other OpenGL extension wrappers like GLEW handle.

**Comment by scheibel** [comment]
We already had some tests and thought about adding these APIs (even together with EGL) but our current approach is to make the xml parser and code generator API agnostic and provide one project per API.
I hope these will come soon, as I took the tests are half a year ago.

**Comment by alexanderbock** [comment]
What is the current status on this issue?  Not being able to use the wgl headers is a dealbreaker for switching from GLEW to glbindings for one of our projects

**Comment by scheibel** [comment]
I moved the issue to our generator project and treat them as two separate issues.

* https://github.com/cginternals/khrbinding-generator/issues/20
* https://github.com/cginternals/khrbinding-generator/issues/21
