### ISSUE TITLE
Update readme (in master) to reflect changed naming/location of functions.h

### ISSUE THREAD

**Issue by flv0** [cginternals/glbinding#134]
I just noticed that the gl/functions\*.h files have been moved to gl\*/functions.h. This needs to be updated in the README. Maybe you intentionally want to wait until the 1.2 release so that the documentation on the project frontpage reflects how things are in the latest release. In that case just see it as a reminder for when the release gets done :smile:

**Comment by flv0** [comment]
Just seeing the commit, I think this can be closed then. Btw if you wrote closes #134 instead of fixes, the commit would have closed the ticket automatically. Thanks!

**Comment by scheibel** [comment]
This ticket would have been closed with the ```fixes``` in the same way ```closes``` does. But as this commit is not yet in the main branch of the repository, GitHub doesn't apply those rules to the tickets yet. Instead, GitHub applies them during the merge.

**Comment by flv0** [comment]
Ah I understand. Thanks for clarification!
