### ISSUE TITLE
Make precompiled headers optional (VS2013)

### ISSUE THREAD

**Issue by traits** [cginternals/glbinding#140]
I'm running into the following issue, when trying to build a Release version of glbindings with a Makefile x64 cmake generator for Visual Studio 2013:

    [ 10%] Building CXX object source/glbinding/CMakeFiles/glbinding.dir/source/Meta
    _FunctionStringsByExtension.cpp.obj
    cl : Command line warning D9025 : Binding_list.cpp
    overriding '/W3' with '/W4'
    V:\libs\src\glbinding\source\glbinding\source\Binding_list.cpp(2) : fatal error
    C1083: Cannot open precompiled header file: 'Binding_pch.pch': No such file or d
    irectory
    jom: V:\libs\build\VS2013\glbinding\Release\source\glbinding\CMakeFiles\glbindin
    g.dir\build.make [source\glbinding\CMakeFiles\glbinding.dir\source\Binding_list.
    cpp.obj] Error 2
    Meta_getStringByBitfield.cpp
    cl : Command line warning D9025 : overriding '/W3' with '/W4'
    cl : Command line warning D9025 : overriding '/W3' with '/W4'
    cl : Command line warning D9025 : overriding '/W3' with '/W4'
    cl : Command line warning D9025 : overriding '/W3' with '/W4'
    cl : Command line warning D9025 : overriding '/W3' with '/W4'
    cl : Command line warning D9025 : overriding '/W3' with '/W4'
    cl : Command line warning D9025 : overriding '/W3' with '/W4'
    Meta_BitfieldsByString.cpp
    Meta_BooleansByString.cpp
    Meta_EnumsByString.cpp
    Meta_ExtensionsByFunctionString.cpp
    Meta_ExtensionsByString.cpp
    Meta_FunctionStringsByExtension.cpp
    jom: V:\libs\build\VS2013\glbinding\Release\CMakeFiles\Makefile2 [source\glbindi
    ng\CMakeFiles\glbinding.dir\all] Error 2
    jom: V:\libs\build\VS2013\glbinding\Release\Makefile [all] Error 2
    v:\libs\scripts>

Would it be possible, to make the entire precompiled header inclusion an option? 

Decreasing build-time is multi-faceted and some approaches tend to stay on each others toes. In my particular use case, build duration is not an issue at all, in contrast to the build scriptings maintenance robustness.

**Comment by scheibel** [comment]
Do you apply custom compiler options, defitions or flags? What is your MSVC 2013 Update? Using our setup, the preconfigured setup compiles without problems.

The actual problem seems to be that the precompiled header couldn't be generated or found afterwards.

**Comment by traits** [comment]
> What is your MSVC 2013 Update?

VS 2013 Professional, Update 5

The Standard cmake generator for VS solution files is working, but the Makefile-based one using jom is not, same for the nmake-based "NMake Makefiles". My command line is:
```
v:\libs\build\VS2013\glbinding\Release>!CMAKE_CMD! v:\libs\src\glbinding -G "NMake Makefiles JOM"  -DOPTION_BUILD_TESTS=OFF -DOPTION_BUILD_TOOLS=OFF -DCMAKE_INSTALL_PREFIX=v:\libs\build\VS2013\glbinding\Release\install -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release
 ```
The VC environment is correct and als !CMAKE_CMD! expands to a valid cmake.exe (v3.4.1)

**Comment by scheibel** [comment]
Okay, we can discuss about making precompiled headers optional, but the error you encounter should be fixed anyway.
We will test an NMake setup.

**Comment by cgcostume** [comment]
created a nmake_makefiles branch, @traits can you please check if you can build this branch

**Comment by traits** [comment]
This works (even for VS 2015). 

Some small nit-pickings (don't satisfy an extra issue):
OPTION_BUILD_TOOLS is ON by default (readme.md states otherwise). As with OPTION_BUILD_TESTS it causes a dependency to GLFW (cmake will complain, if not found). readme.md claims, that GLFW is only required by examples (no tests, no tools), this should be clarified.

Personally I wouldn't turn any of these options on by default for this reason. glbindings is rather fundamental. It should maintain maximal orthogonality to any particular context-providing library for standard builds (from an users point of view glbinding will be very likely part of some comprehensive batch of build scripts for a dozen different libraries) .

PYTHON vs PYTHON_EXECUTABLE: Finally,I let both of them point to my python(v2) binary. What is the intended difference?

**Comment by cgcostume** [comment]
@traits Thanks for your feedback: we discussed the default settings a few weeks ago internally, currently there will be no future changes intended. Concerning the readme.md, yes, we are going to revisit the readme and the wiki in a few days. Sorry for any inconvenience.

The ```PYTHON_EXECUTABLE``` is created by ```FindPythonInterp.cmake``` (maintained by CMake) when our code generation cmake script calls ```find_program(PYTHON "python")```. So ```PYTHON``` is created by our cmake configuration and is used to generate the binding.
