### ISSUE TITLE
Getting rid of dll-interface warnings when compiling on Windows

### ISSUE THREAD

**Issue by totalgee** [cginternals/glbinding#141]
Sorry, this is possibly a dumb thing (I hope so) -- I've not developed much on Windows in recent years, but am now porting an OS X OpenGL application to Windows 10 (using Visual Studio 2015).  I’m using the downloaded (pre-built) Windows version of glbinding (from [here](https://github.com/cginternals/glbinding/releases/download/v1.1.0/glbinding-1.1.0-msvc12-x64-dev.zip)).  What do I need to change (a define or a project compilation setting?) to get rid of the huge number of warnings that appear that look something like this:

```
...\glbinding\include\glbinding\binding.h(47): warning C4251: ‘glbinding::Binding::Accum’: class ‘glbinding::Function<void,gl::GLenum,gl::GLfloat>’ needs to have dll-interface to be used by clients of class ‘glbinding::Binding’
```

These warnings occur when compiling the .cpp file that includes `glbinding/Binding.h`. Do I need to recompile glbinding as a static library? (I'd prefer to use the pre-built version if at all possible, which seems to be a dynamic-linking version.)

By the way, these are warnings, not errors.  The project otherwise compiles, links and seems to run correctly.  But there are a huge number of them (hundreds or thousands), and they'll make it harder to spot real warnings.  I can just disable the warning, but it seems this may not be the best solution...?

I've seen some threads discussing this warning (e.g. [here](http://stackoverflow.com/questions/16419318/one-way-of-eliminating-c4251-warning-when-using-stl-classes-in-the-dll-interface) or [here](http://stackoverflow.com/questions/5661738/how-can-i-use-standard-library-stl-classes-in-my-dll-interface-or-abi)).  But I'm not sure what's the best thing to do in my case, as I'm not the one creating a DLL, just using the existing glbinding library in an executable.

Thanks for any help you can offer,
Glen.

**Comment by totalgee** [comment]
The compiler warning page for C4251 is [here](https://msdn.microsoft.com/query/dev14.query?appId=Dev14IDEF1&l=EN-US&k=k(C4251)&rd=true).

The warnings appear for three glbinding headers (callbacks.h, abstractfunction.h, binding.h), and seem to be due to deriving from classes using STL features like std::vector, std::function or std::chrono. Here I just show one example from each file:

```
Warning	C4251	'glbinding::FunctionCall::timestamp': class 'std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>' needs to have dll-interface to be used by clients of struct 'glbinding::FunctionCall'	c:\libs\glbinding\include\glbinding\callbacks.h	29

Warning	C4251	'glbinding::AbstractFunction::m_states': class 'std::vector<glbinding::AbstractFunction::State,std::allocator<_Ty>>' needs to have dll-interface to be used by clients of class 'glbinding::AbstractFunction'	c:\libs\glbinding\include\glbinding\abstractfunction.h	79

Warning	C4251	'glbinding::Binding::Accum': class 'glbinding::Function<void,gl::GLenum,gl::GLfloat>' needs to have dll-interface to be used by clients of class 'glbinding::Binding'	c:\libs\glbinding\include\glbinding\binding.h	47
```

Any Windows experts got an idea, or come across this before?

**Comment by scheibel** [comment]
glbinding-1.1.0 is somehow an old release (it is the current one, but a new release is long due) and we changed a lot in our build-system and also work on the warning you issued. Can you test building the glbinding master from source? We assume that the errors will disappear.

**Comment by totalgee** [comment]
Thanks, I'm trying that.  I installed the latest CMake (3.4.2), then loaded up the glbinding source directory in cmake-gui.  When I try to Configure, I choose the generator "Visual Studio 14 2015 Win64", with default native compilers.  Then I get "Error in configuration process, project files may be invalid."

```
CMake Error at CMakeLists.txt:69 (project):
  Could not find an appropriate version of the Windows 10 SDK installed on
  this machine
```
Under `C:\Program Files\Windows Kits`, I have both 8.1 and 10. Under 10\Lib (or 10\Include), I have two versions: `10.0.10150.0` and `10.0.10240.0`.  I seem to have both 8.1 and a couple of Windows 10 SDKs installed, as far as I understand (granted, I'm not very familiar with Windows development).

Any suggestions on how to proceed? I tried setting `CMAKE_SYSTEM_VERSION` to various values (e.g. 8.1, 10.0, 10.0.10240.0), with no luck. I've just found a thread that talks about a [Microsoft fork of CMake](https://github.com/Microsoft/CMake), should I have installed that instead?

Thanks.

**Comment by totalgee** [comment]
It worked if I used the Microsoft fork of CMake.  For reference, here's what I did after installing CMake.

I opened a "VS2015 x64 Native Tools Command Prompt" and changed to the directory where I had glbinding's source code from master. Then:

```
> mkdir build
> cd build
> cmake -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_INSTALL_PREFIX=C:/libs/glbinding -G "Visual Studio 14 2015 Win64" ..
> devenv glbinding.sln /build Release /project INSTALL
```

**Comment by cgcostume** [comment]
FYI, our jenkins configuration for msvc2015:

Environment Setup:
```
_GLFW_DIR = $WORKSPACE/../glfw-windows-msvc2015
_GLEW_DIR = $WORKSPACE/../glew-windows-msvc2015
_PYTHON_DIR = C:/utils/python-2.7.8
_DOXYGEN_DIR = C:/utils/doxygen-1.8.7
_GRAPHVIZ_DIR = C:/utils/graphviz-2.38
_NSIS_DIR = C:/utils/nsis-3.0b1
_QT_DIR = C:/3rdp/Qt/5.5/msvc2015_64
_WINDOWS_SDK = C:/Program Files (x86)/Windows Kits/8.1
QT_QPA_PLATFORM_PLUGIN_PATH = $_QT_DIR/plugins/platforms
CMAKE_PREFIX_PATH = $_WINDOWS_SDK/Lib/winv6.3/um/x64;$_GLEW_DIR;$_GLFW_DIR;$_QT_DIR;$_PYTHON_DIR;
Path = $_GRAPHVIZ_DIR/bin;$_GLFW_DIR/bin;$_QT_DIR/bin;$_DOXYGEN_DIR/bin;$_NSIS_DIR/bin;$_PYTHON_DIR;$_WINDOWS_SDK/bin/x64;$_GLEW_DIR/bin/Release/x64;$_GLEW_DIR/bin/Debug/x64;$PATH
```

Build:
```
IF exist build (rd /S /Q build)

mkdir build
cd build

call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall" amd64
set CL=/MP
cmake .. -G "Visual Studio 14 2015 Win64" -DOPTION_BUILD_EXAMPLES=On -DCMAKE_INSTALL_PREFIX="." || exit /b

echo.
echo RUN CODEGENERATION
msbuild codegeneration\generate.vcxproj /ds /m /verbosity:m /nologo || exit /b

echo.
echo BUILD DEBUG
msbuild ALL_BUILD.vcxproj /p:Configuration=Debug /ds /m /verbosity:m /nologo || exit /b

echo.
echo TEST DEBUG
msbuild source\tests\test.vcxproj /p:Configuration=Debug /m /verbosity:m /nologo || exit /b

echo.
echo INSTALL DEBUG
msbuild INSTALL.vcxproj /p:Configuration=Debug /ds /m /verbosity:m /nologo || exit /b

echo.
echo BUILD RELEASE
msbuild ALL_BUILD.vcxproj /p:Configuration=Release /ds /m /verbosity:m /nologo || exit /b

echo.
echo TEST RELEASE
msbuild source\tests\test.vcxproj /p:Configuration=Release /m /verbosity:m /nologo || exit /b

echo.
echo INSTALL RELEASE
msbuild INSTALL.vcxproj /p:Configuration=Release /ds /m /verbosity:m /nologo || exit /b
```

**Comment by totalgee** [comment]
So with the statically-linked version (from master), obviously I get none of the linker warnings (C4251). However, with the dynamic-linked version (compiled using `-DBUILD_SHARED_LIBS:BOOL=ON`, which is also the default), I still get the above-mentioned warnings when linking an application with the library, as I did with v1.1.0.

At least I can get rid of the warnings (or, better, limit them to appearing once) like this:

```c++
#include <glbinding/gl41core/gl.h>
#pragma warning(once: 4251)
#include <glbinding/Binding.h>
#pragma warning(default: 4251)
using namespace gl41core;
```

**Comment by cgcostume** [comment]
For building glbinding we disable 4251 (see ```cmake/CompileOptions.cmake```). So i suggest to disable the warning for your projects as well, since it probably will not be resolved.

**Comment by totalgee** [comment]
Ah, well that makes sense. Thanks, that's what I'd done. Good to have
confirmation!

**Comment by totalgee** [comment]
Sounds like there's nothing more to say about this for now...closing.
