### ISSUE TITLE
PPA for Debian/Ubuntu based systems?

### ISSUE THREAD

**Issue by SirVer** [cginternals/glbinding#143]
[This wiki page](https://github.com/cginternals/glbinding/wiki/Install#debian-based-systems) suggests to use the PPA for your system. 

I was unable to find links to official PPAs in the wiki or docs though. Did I just miss it?

**Comment by SirVer** [comment]
cc @TinoM

**Comment by scheibel** [comment]
You didn't miss anything. The wiki page was pretty optimistically written regarding our progress with the packaging systems.
Maybe it's best to remove those lines and re-add them once we actually have the PPA, RPM, WIX, and AppBundle packages.

**Comment by scheibel** [comment]
FYI: there is one PPA for glbinding which we don't maintain ourselves: https://launchpad.net/~makson96/+ppa-packages

**Comment by SirVer** [comment]
that particular PPA seems to have been last updated ~1 year ago for glbinding. That seems less than ideal.

Just from my experience with [Widelands](https://launchpad.net/widelands): setting up a PPA on launchpad is rather quick (< 2 hours) and painless and it increases the outreach on Linux tremendously. I would very much appreciate it, because I'd like to switch Widelands PPA to build against glbinding instead of glew, but that requires either bundling glbinding in our repo or a PPA.

**Comment by scheibel** [comment]
It took me quite a bit longer than two hours but all upcoming projects/builds should be significantly faster.
Maybe you want to try https://launchpad.net/~cginternals/+archive/ubuntu/ppa.

**Comment by SirVer** [comment]
I am sorry that it took longer, but the cooler that you did it anyways :) Thank you.

I saw that Trusty and Vivid builds are not available - especially trusty would be very cool to have. My guess is that you are missing a modern c++11 compiler on these platforms, right? 

You can fix that by marking your PPA depending on https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test which contains gcc-5. Then you can just add that to your build-depends in your debian/control file.

**Comment by SirVer** [comment]
My first build test against the PPA was not successful. It managed to install glbinding, but [this line](http://bazaar.launchpad.net/~widelands-dev/widelands/trunk/view/head:/CMakeLists.txt#L60) in your CMakeLists.txt fails with these weird outputs:

~~~
CMake Error at cmake/WlFunctions.cmake:98 (wl_include_system_directories):
  wl_include_system_directories Function invoked with incorrect arguments for
  function named: wl_include_system_directories
Call Stack (most recent call first):
  cmake/WlFunctions.cmake:175 (_common_compile_tasks)
  src/graphic/CMakeLists.txt:86 (wl_library)


CMake Error at cmake/WlFunctions.cmake:98 (wl_include_system_directories):
  wl_include_system_directories Function invoked with incorrect arguments for
  function named: wl_include_system_directories
Call Stack (most recent call first):
  cmake/WlFunctions.cmake:175 (_common_compile_tasks)
  src/graphic/CMakeLists.txt:145 (wl_library)


CMake Error at cmake/WlFunctions.cmake:98 (wl_include_system_directories):
  wl_include_system_directories Function invoked with incorrect arguments for
  function named: wl_include_system_directories
Call Stack (most recent call first):
  cmake/WlFunctions.cmake:175 (_common_compile_tasks)
  src/graphic/CMakeLists.txt:215 (wl_library)
~~~

[Full build log for wily](https://launchpadlibrarian.net/235295483/buildlog_ubuntu-wily-amd64.widelands_1%3A18-ppa0-bzr7746-201601261934~ubuntu15.10.1_BUILDING.txt.gz)

Do you have a clue what the problem might be?

**Comment by scheibel** [comment]
Another main problem with vivid and trusty is the available cmake-version which we can also fix with another PPA.

**Comment by scheibel** [comment]
Regarding the errors in your log: I don't think this is a glbinding-related issue (the function starts with a ```wl_```). Maybe there is a problem related to the recent build-system update of glbinding (around 4 weeks ago)?

Does widelands generally compile using our current glbinding?

**Comment by SirVer** [comment]
Yes, it build fine on Mac OS with a brewed version from yesterday (1.1.0) and with a self build version on Linux. Not sure how current that is compared to HEAD though. 

Mmmh, your comment about cmake makes me think that 1.1.0 is different than head. The cmake version might be a problem. The glbinding README.md still states  CMake 2.8.12 btw.

**Comment by scheibel** [comment]
I'm playing around with PPAs for a little longer and want to inform you about a breaking change: in a few minutes/hours, the ```glbinding``` package will be named ```libglbinding-all``` (separating the components configured with cmake for the PPAs seems quite challenging).

**Comment by SirVer** [comment]
thank you - I backed out using glbinding for Widelands for the moment. Could you ping me here once you are happy with the PPA state?

**Comment by scheibel** [comment]
I'll ping you if we're happy with the PPA setup.

**Comment by scheibel** [comment]
We now have two PPAs with separated packages for the glbinding components on launchpad:
 * https://launchpad.net/~cginternals/+archive/ubuntu/ppa (for xenial and wily)
 * https://launchpad.net/~cginternals/+archive/ubuntu/backports-ppa (for vivid, requiring a PPA for a current cmake)

Supporting one additional PPA for trusty may be possible but for that we would have to create additional *recipes* (for trusty, the ```libglfw3-dev``` package seems to be named ```libglfw3``` and is accessible through another PPA).

In each PPA, there are the following packages:
 * libglbinding
 * libglbinding-dev
 * libglbinding-dbg
 * libglbinding-tools
 * libglbinding-examples
 * libglbinding-all (all of the above without the *-dev package)

Currently known bugs: shaders from libglbinding-examples are not found.

Can you work with that? Are they working for you?

**Comment by SirVer** [comment]
Thanks for your work on this. I can try setting up a Widelands PPA for wily and vivid on the weekend and test it out. Unfortunately without trusty we cannot switch to glbinding as a default for our PPA, since that is the lowest version we are targetting.

**Comment by scheibel** [comment]
The build-farm was pretty busy yesterday, but now we also have a third PPA for trusty: https://launchpad.net/~cginternals/+archive/ubuntu/trusty-backports-ppa
I didn't test the packages myself yet (only our servers run trusty, maybe I can test them today), but if they can be built...

**Comment by scheibel** [comment]
Small correction: I move the packages from the aforementioned PPA for Ubuntu trusty to the normal backports PPA for Ubuntu vivid. There is no libglfw3-dev package for trusty available, which impairs the packaging of the examples and tools but not the actual library or development files.

**Comment by SirVer** [comment]
Sorry, It took me a while to get around to that again. It seems like I can include the PPA and it also seems like the CMakeFiles that ship in libglbinding-dev are found. However, buillding fails, I think I ran into some cmake trouble which might be unrelated to this issue.

In my CMakeLists.txt [I am searching for glbinding](http://bazaar.launchpad.net/~widelands-dev/widelands/ppa_glbinding/view/head:/CMakeLists.txt#L65). But even though the `find_package(glbinding REQUIRED)` is succeeding none of `GLBINDING_INCLUDES`, `GLBINDING_INCLUDE_DIRS` or `GLBINDING_INCLUDE_DIRS` is set. I [print out all CMakeVariables](http://bazaar.launchpad.net/~widelands-dev/widelands/ppa_glbinding/view/head:/CMakeLists.txt#L71) and cannot find any of the information. My linking step then fails because glbinding is not linked into my executable. Any ideas?

[Full build log](https://launchpadlibrarian.net/236748198/buildlog_ubuntu-xenial-amd64.widelands_1%3A18-ppa0-bzr7793-201602061113~ubuntu16.04.1_BUILDING.txt.gz). Search for `Looking for glbinding` to find the output of the code linked above.

**Comment by sbusch42** [comment]
Yes, we converted to modern cmake ways, which are to export the project instead of using cmake variables. To link against it, you simply use 
  target_link_libraries(yourTarget glbinding::glbinding)
in your project. This will not only add the library to the linker, but also import the include paths and compiler definitions the project exports.

**Comment by SirVer** [comment]
Is there a way to detect if I am using pre-modern-world-cmake? The version I got via brew install definitively sets the variables I mentioned and I need to support both ways.

**Comment by SirVer** [comment]
Our [PPA built and runs](https://code.launchpad.net/~sirver/+archive/ubuntu/widelands-daily/) fine using the glbinding PPA. Tested for Trusty, Vivid, Wily, Xenial. I think this issue can be closed now.

@scheibel Thanks for your help with this!

**Comment by cgcostume** [comment]
Use single recipe  instead of multiple ones, and add documentation target/package (glbinding-docs).

**Comment by scheibel** [comment]
I refined the PPAs one more time. Now we provide two PPAs for the following Ubuntu versions:
 * standard PPA
  * Xenial
  * Wily
  * Vivid
 * backports PPA
  * Trusty
