### ISSUE TITLE
Lack of pkg-config compatibility

### ISSUE THREAD

**Issue by zesterer** [cginternals/glbinding#144]
The title says it all. I'd love (need) to use this library with pkg-config.

**Comment by scheibel** [comment]
We'll have a look at it.
Do you have a good source on how to implement this feature? What is missing?
Of course I will use google but I assume I will find multiple ways.

**Comment by zesterer** [comment]
pkg-config is a relatively standard little program that provides an easy way to find flags and directories for libraries. It tends to be used mostly on linux.

**Comment by zesterer** [comment]
Here's a good guide: http://people.freedesktop.org/~dbn/pkg-config-guide.html

**Comment by scheibel** [comment]
Thanks.
My first search indicates that no actual cmake <-> pkg-config integration is available.
It seems like we have to generate a ```.pc``` file using the ```configure_file``` function from cmake and install it with the dev-component.

@sbusch42, @cgcostume: This may be a change/feature we want to integrate into cmake-init.

**Comment by scheibel** [comment]
This issue is continued in [cmake-init](https://github.com/cginternals/cmake-init/issues/60) and will get ported to glbinding once its done in cmake-init.
