### ISSUE TITLE
glTexImage2D -> internalformat

### ISSUE THREAD

**Issue by tomkulaga** [cginternals/glbinding#146]
glTexImage2D vs glTexImage2DMultisample

I've checked the reference for the functions and glBinding agress with them, but I'm having trouble understanding whether glTexImage2D should take a GLenum as the internalfomat parameter, as all the format types are GLenums not Glints. Unless I am mistaken ?

**Comment by scheibel** [comment]
First of all, it isn't your fault or understanding problem. Sereval glbinding users have this issue (https://github.com/cginternals/glbinding/issues/125, https://github.com/cginternals/glbinding/issues/119, https://github.com/cginternals/glbinding/issues/107, https://github.com/cginternals/glbinding/issues/74), including ourselves (https://github.com/cginternals/glbinding/issues/108).

This is a problem with the OpenGL API that is designed for a C interface with no overloading in mind. Where type-safety would be a problem, suffixes on the function names were introduced (f for ```float```, ui for ```unsigned int```, ...). You found functions where the *overloading* with different castable types is actually desired, but glbinding want to strictly separate basic integer values from ```GLenums```. We plan to Integrate several more fixes regarding these ```GLint```/```GLuint```/```GLenum``` parameters issues. But for now, you just have to use a ```static_cast``` when passing the parameter.

**Comment by cgcostume** [comment]
will be addressed in #108 for glbinding v2.0
