### ISSUE TITLE
Retest doxygen configuration, use gh-pages for deployment.

### ISSUE THREAD

**Issue by cgcostume** [cginternals/glbinding#149]
The doxygen documentation should reside ```documentation``` directory within the ```gh-pages``` branch.
Should be accessible via https://cginternals.github.io/glbinding/documentation then.

**Comment by julkw** [comment]
The link now works and shows the documentation for the current commit on the glbinding-2.0-release branch. Should I also add a link to the documentation on the main page?

**Comment by scheibel** [comment]
Yes. Thanks.

**Comment by julkw** [comment]
I added the link in a banner next to the GitHub link. Is that ok or do you want me to put it somewhere else on the page?

**Comment by julkw** [comment]
I added a link in the README.md and on the main page of the gh-pages (https://cginternals.github.io/glbinding) which is what I initially meant.

**Comment by scheibel** [comment]
Note for future developer/self: the documentation is currently a manual copy of the generated doxygen html directory from a self-triggered build.

However, it is integrated into the github.io page of glbinding.
