### ISSUE TITLE
Adapt doxygen style to cginternals CI as much as possible

### ISSUE THREAD

**Issue by cgcostume** [cginternals/glbinding#150]
this includes at least new logos, and possible new template (e.g., https://github.com/Velron/doxygen-bootstrapped)

**Comment by scheibel** [comment]
I recall that we want to keep the default Doxygen template instead of providing high-maintenance own versions.
I suggest we reduce the scope of this issue accordingly.

**Comment by scheibel** [comment]
Refs #248.
