### ISSUE TITLE
Extract Meta interface into glbinding-meta submodule.

### ISSUE THREAD

**Issue by scheibel** [cginternals/glbinding#154]

**Comment by cgcostume** [comment]
current planning for the two modules:
* **glbinding** comprising the core elements required for the OpenGL binding
* **glbinding-x** e**x**tending the core library with introspection and logging/error checking capabilities 

Note: glbinding-x will not contain glbinding, but extend it (and depend on it).

The contents of ***glbinding-x*** will be:
* logging: continuous, asynchronous logging
* string to symbol and symbol to string conversion (current ```Meta```)
* deprecation information
* runtime error checks 
* context information  (current ```ContextInfo```)
* perhaps in future releases: device information

We are open for suggestions to the name and features of the extended glbinding library (vote for names below).

**Comment by cgcostume** [comment]
glbinding-tm :  **t**ell **m**e

**Comment by cgcostume** [comment]
glbinding-ccc : **c**ross **c**utting **c**oncerns

**Comment by cgcostume** [comment]
glbinding-x : e**x**tended

**Comment by cgcostume** [comment]
glbinding-mp : **m**issing **p**iece

**Comment by karyon** [comment]
glbinding-ext : extra, extended, extensions

EXT is used for opengl extensions, that might good because it's familiar, or bad because people might think they find the opengl extensions in there or something...

**Comment by cgcostume** [comment]
@karyon thanks for the suggestion, due to you second (bad)remark we will not use **ext** (we discussed this internally already when coming up with some candidates)

**Comment by sbusch42** [comment]
glbinding-aux (auxiliary functionality)

**Comment by kateyy** [comment]
glbinding-extras (I think there are some debian packages using this naming scheme...)

**Comment by cgcostume** [comment]
it will be glbinding-aux 😉

**Comment by scheibel** [comment]
There is now a `glbinding-aux` module available.
