### ISSUE TITLE
Linking problem

### ISSUE THREAD

**Issue by JKot-Coder** [cginternals/glbinding#156]
Hello. I have some troubles with your project.

Here is my code:

```
#include <glbinding/Binding.h>
#include <glbinding/gl/gl.h>
using namespace gl;

int main(int argc, char *argv[])
{
    glbinding::Binding::initialize();
}
```

Here is my cmake:

```
cmake_minimum_required(VERSION 2.8) 
include(cmake/glbinding-config.cmake)

set (CMAKE_CXX_STANDARD 11)

set(SOURCES main.cpp)
add_executable(main ${SOURCES})

find_package(glbinding REQUIRED)
include_directories(${GLBINDING_INCLUDES})
target_link_libraries(main ${GLBINDING_LIBRARIES})
target_link_libraries(main ${GLBINDING_LIBRARY_RELEASE})
```

On linking I get:
On windows I get: `undefined reference to 'glbinding::Binding::initialize(bool)'`
On linux I get:

```
/usr/local/lib/libglbinding.so: undefined reference to `vtable for glbinding::Function<void, gl::GLenum, int, int*>'
/usr/local/lib/libglbinding.so: undefined reference to `std::function<void (signed char, signed char, signed char, signed char)>::function(decltype(nullptr))'
/usr/local/lib/libglbinding.so: undefined reference to `vtable for glbinding::Function<void, gl::GLenum, long, long, gl::GLboolean>'
/usr/local/lib/libglbinding.so: undefined reference to `vtable for glbinding::Function<void, unsigned int, gl::GLenum, int, gl::GLenum, int, int, int, int>'
```

And thousand similar errors.

On windows I use prebuild package glbinding-1.1.0-msvc12-x64 and mingw compiller. On Linux I use build from sources version v1.1.0. 

What am I doing wrong?

**Comment by scheibel** [comment]
I think it is helpful to know the actual contents of the ```${GLBINDING_LIBRARIES}``` and ```${GLBINDING_INCLUDES}``` variables.
So please add the following lines after the ```find_package(glbinding REQUIRED)``` call
```cmake
message(STATUS "GLBINDING_LIBRARIES = ${GLBINDING_LIBRARIES}")
message(STATUS "GLBINDING_INCLUDES = ${GLBINDING_INCLUDES}")
```
and post the results here. Basically it seems as if the includes but no binaries could be found.

Besides that, your cmake script contains a few lines that seems strange to me:
 * ```CMAKE_CXX_STANDARD``` is introduced with cmake 3.1, so probably your minimum required version should get raised.
 * the ```include(cmake/glbinding-config.cmake)``` shouldn't be required to call and I'm not sure if it doesn't do any harm.
 * Why do you call ```target_link_libraries``` two times where the release library should be included into the libraries variable if found?

**Comment by JKot-Coder** [comment]
I made some changes, as you recommended.
Now cmake looks like this:
```
cmake_minimum_required(VERSION 2.8) 
include(cmake/glbinding-config.cmake)

set(SOURCES main.cpp)

find_package(glbinding REQUIRED)
include_directories(${GLBINDING_INCLUDES})
link_libraries(${GLBINDING_LIBRARIES})

message(STATUS "GLBINDING_LIBRARIES = ${GLBINDING_LIBRARIES}")
message(STATUS "GLBINDING_INCLUDES = ${GLBINDING_INCLUDES}")

add_executable(main ${SOURCES})
```
But nothing changed, after clean build I got same link errors.
The output is
Windows:
```
-- GLBINDING_LIBRARIES = C:/Program Files/glbinding/lib/glbinding.lib
-- GLBINDING_INCLUDES = C:/Program Files/glbinding/include
```
Linux:
```
-- GLBINDING_LIBRARIES = /usr/local/lib/libglbinding.so
-- GLBINDING_INCLUDES = /usr/local/include
```

**Comment by JKot-Coder** [comment]
I actually think maybe I need to build glbinding with mingw on windows, to get mingw libs?

**Comment by scheibel** [comment]
During the meantime glbinding is integrated into MinGW distributions (e.g., https://nuwen.net/mingw.html). Please reopen if your problem persists.
