### ISSUE TITLE
cmake retro-compatibility issue

### ISSUE THREAD

**Issue by Ryp** [cginternals/glbinding#167]
`GLBINDING_LIBRARIES` is not defined anymore in release 2.0, this should be mentioned in the changelog since it's breaking at link-time for existing cmake applications.

Seems like `GLBINDING_LIBRARY_RELEASE` or `GLBINDING_LIBRARY_DEBUG` should be used instead, at least that's what i used.

**Comment by scheibel** [comment]
Thanks for noticing, we will add this breaking change to the change log.
Additionally, I want to add our intended linking of glbinding into own projects.

As far as I know, our current way to link glbinding into other projects is supported with CMake 2.6 and higher. In the deployed ```glbinding-export.cmake``` file there are commands that define target properties of a ```glbinding::glbinding``` target:
```cmake
set_target_properties(glbinding::glbinding PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "$<$<NOT:$<BOOL:ON>>:GLBINDING_STATIC_DEFINE>;SYSTEM_LINUX"
  INTERFACE_COMPILE_OPTIONS "-Wall;-Wextra;-Wunused;-Wreorder;-Wignored-qualifiers;-Wmissing-braces;-Wreturn-type;-Wswitch;-Wswitch-default;-Wuninitialized;-Wmissing-field-initializers;$<$<CXX_COMPILER_ID:GNU>:;-Wmaybe-uninitialized;$<$<VERSION_GREATER:$<CXX_COMPILER_VERSION>,4.8>:;-Wpedantic;-Wreturn-local-addr;>;>;$<$<CXX_COMPILER_ID:Clang>:;-Wpedantic;-Wreturn-stack-address;>;$<$<PLATFORM_ID:Darwin>:;-pthread;>;$<$<VERSION_LESS:3.2.2,3.1>:;-std=c++11;>"
  INTERFACE_INCLUDE_DIRECTORIES "/home/willy/cginternals/glbinding/source/glbinding/include;/home/willy/cginternals/glbinding/build-debug/source/glbinding/include"
  INTERFACE_LINK_LIBRARIES "/usr/lib/x86_64-linux-gnu/libGLU.so;/usr/lib/x86_64-linux-gnu/libGL.so;-pthread"
)
```
Later you can link your own target against ```glbinding::glbinding``` and CMake handles everything from include directories, libraries and additional compiler definitions:
```cmake
target_link_libraries(${target}
    PRIVATE
    glbinding::glbinding
)
```

**Comment by scheibel** [comment]
I updated the changelog (https://github.com/cginternals/glbinding/releases/tag/v2.0.0).
