### ISSUE TITLE
Interface compile options contain warning flags

### ISSUE THREAD

**Issue by nazar554** [cginternals/glbinding#170]
Recently I had a problem with my project when I linked to glbinding imported target because of various warning flags (my project builds with -Werror). Can you remove them from `INTERFACE` compile options?

What I mean:
`glbinding-export.cmake`
```
set_target_properties(glbinding::glbinding PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<NOT:\$<BOOL:ON>>:GLBINDING_STATIC_DEFINE>;SYSTEM_WINDOWS"
  # Everything until -pthread is unneeded and messes up my project
  INTERFACE_COMPILE_OPTIONS "-Wall;-Wextra;-Wunused;-Wreorder;-Wignored-qualifiers;-Wmissing-braces;-Wreturn-type;-Wswitch;-Wswitch-default;-Wuninitialized;-Wmissing-field-initializers;\$<\$<CXX_COMPILER_ID:GNU>:;-Wmaybe-uninitialized;\$<\$<VERSION_GREATER:\$<CXX_COMPILER_VERSION>,4.8>:;-Wpedantic;-Wreturn-local-addr;>;>;\$<\$<CXX_COMPILER_ID:Clang>:;-Wpedantic;-Wreturn-stack-address;>;\$<\$<PLATFORM_ID:Darwin>:;-pthread;>;\$<\$<VERSION_LESS:3.4.1,3.1>:;-std=c++11;>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "glu32;opengl32;-pthread"
)
```

**Comment by scheibel** [comment]
There are two ways to solve this issue and maybe both of them should be implemented.
The first one is that we exclude the warnings from our interface options. Thanks for the hint.
The second one is the declaration of the glbinding includes as ```system``` includes in the ```glbinding-export.cmake``` file. That would work for all compilers that understand the concept of system includes (GCC and Clang knows the concept, however, MSVC seems not).

**Comment by TimNN** [comment]
I just ran into the same problem (and spend a lot of time debugging it): I wanted to silence some other warning (`-Wno-unknown-pragmas`) however this proved difficult / impossible since I could not find a way to add this flag **after** the `-Wall` added by glbindings. Maybe i'll find a way to do this now that I know the flag is added by glbindings.

**Comment by cgcostume** [comment]
ref 8ebf9498258337b98ed5f6fc957d0d7791a8d7be

**Comment by cgcostume** [comment]
@TimNN thanks a lot for reporting. Can you please retry with the latest master (or the upcoming 2.1 tag).

**Comment by TimNN** [comment]
I don't really remember what I was thinking / doing back then, but from a short test I believe my issue has been fixed.

**Comment by scheibel** [comment]
Thanks for the info.
