### ISSUE TITLE
find_package(glbinding REQUIRED) returns nothing

### ISSUE THREAD

**Issue by FrostedPenguin** [cginternals/glbinding#171]
Hi. I've some issues with glbinding.

I'm using ubuntu 15.10 and installed glbinding using this commands

`sudo apt-add repository ppa:cginternals/ppa`
`sudo apt-get update`
`udo apt-get install libglbinding-examples-glfw`

`sudo apt-get install libglbinding-dev libglbinding-dbg`
I've checked cube example and it works well so I'm pretty sure it is installed successfully

However my cmake cannot find glbinding.
I have used this
`find_package(glbinding REQUIRED)`

but 

`message(STATUS "GLBINDING_LIBRARIES = ${GLBINDING_LIBRARIES}")`
`message(STATUS "GLBINDING_INCLUDES = ${GLBINDING_INCLUDES}")` 

returns nothing.

So instead of using find_package, I just hardcoded the location of libglbinding.so

How can I solve this problem? Do you have any idea?

**Comment by scheibel** [comment]
The intended way to use the results of the glbinding find script is:
```cmake
target_link_libraries(${target}
    PRIVATE
    glbinding::glbinding
)
```
This call configures your target to link against the glbinding library and it also adds compiler options and include directories. (further info: https://github.com/cginternals/glbinding/issues/167).

**Comment by FrostedPenguin** [comment]
Thanks. It works. However it works when I didn't use PRIVATE keyword.
`
target_link_libraries(${target}
    glbinding::glbinding
)
`
When I use PRIVATE or PUBLIC keyword cmake spit these errors.

> CMake Error at CMakeLists.txt:39 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "renderer".  All uses of target_link_libraries with a target
  must be either all-keyword or all-plain.

  The uses of the plain signature are here:

I'm quite new to CMake so i don't know much about these but would you explain what they are?
But I just wonder and I want to make sure that I'm not missing something

**Comment by scheibel** [comment]
It seems as if you added ```glbinding::glbinding``` with the private keyword after you added some other libraries without preceding visibility declaration. CMake wants you to chose if you want to assign a visibility to all of them or none of them. It won't allow a mix.
You can omit the private keyword and as I just saw, our readme of glbinding uses the public keyword.

**Comment by sbusch42** [comment]
I can only interpret the error message you posted, which you could also do yourself.

It seems that you have already used target_link_libraries(renderer ...) in your CMakeLists.txt. Now you call it again with target_link_libraries(renderer PRIVATE ...). That seems not to be supported by cmake, you either always use PRIVATE/PUBLIC/INTERFACE or you never use it, you cannot mix. That seems to be the error in your CMakeLists.txt.

I would recommend to read the cmake documentation and decide on your own style. CMake has evolved a lot and their are "old ways" and "new ways". Both are totally OK, but one shouldn't mix them. You really have to decide on your own cmake style you want to use in your project and stick to that. Our you could use a template such as cmake_init which does that for you :)

**Comment by FrostedPenguin** [comment]
Thank you guys. Both of replies really helpful for me. 
And as you said, I will check cmake_init out.

**Comment by scheibel** [comment]
In case you may find other projects named cmake-init, we talk about this one: https://github.com/cginternals/cmake-init.
