### ISSUE TITLE
RingBuffer.h and RingBuffer.hpp include each other

### ISSUE THREAD

**Issue by StephanTLavavej** [cginternals/glbinding#172]
https://github.com/cginternals/glbinding/blob/master/source/glbinding/source/RingBuffer.h#L59 says:
`#include "RingBuffer.hpp"`

https://github.com/cginternals/glbinding/blob/master/source/glbinding/source/RingBuffer.hpp#L10 says:
`#include "RingBuffer.h"`

Although they're guarded with `#pragma once`, this mutual inclusion is really undesirable. If the .h is meant to provide only the class definition, then it shouldn't include the .hpp. If they're both meant to be synonyms and to provide the complete implementation, then the class definition and following implementation should appear in one file, which is then included by the other.

**Comment by scheibel** [comment]
The semantic behind this bidirectional inclusion is the separation between interface and implementation, as it is done in C++ with header and cpp files. With this in mind, an implementation has to include its header. But as the header defines templates which must provide their implementation with them, the header includes the implementation as well.

A nice side consequence is that you can include either the ```.h``` or ```.hpp``` file. I know of C++ projects that deploy their header with a ```.h``` extension, some with a ```.hpp``` extension and even some without any extension. I'm not sure if people using the second style would use the ```.h``` include if both are present.

From our point of view, we could remove the include from the ```.hpp``` to the ```.h``` file.
Do you have a more thorough explanation why bidirectional inclusion is undesirable?

**Comment by StephanTLavavej** [comment]
It usually indicates programmer confusion. If you've intentionally done this, I suppose it's okay, but it would be more straightforward to put the class definition, followed by the implementation, in one header, and have the other header include it (and be otherwise empty) to be a synonym. Then readers can still see the separate class definition (to quickly view the structure of the code), but they can also see that the template implementation is always available.

Feel free to resolve this as "by design". I was just very surprised when I saw this mutual inclusion pattern, as I never use it (and I work on templates all day, every day).

**Comment by StephanTLavavej** [comment]
Closing my issue - I thought this was a mistake, but it turned out to be intentional, and nothing is physically harmful here. No need to waste your time worrying about this.

**Comment by cgcostume** [comment]
thanks @StephanTLavavej for your comments and remarks. We are discussing this issue: reopened for pending design decision.
