### ISSUE TITLE
glbinding compatibility with OpenCL headers for CL-GL interop

### ISSUE THREAD

**Issue by 9prady9** [cginternals/glbinding#176]
There seems to be an issue using glbinding headers with OpenCL c++ headers provided by Khronos. You can find the header [here](https://www.khronos.org/registry/cl/api/2.1/cl.hpp).

Most of the errors i found are along the lines of the below one

``` c
error: cannot convert ‘gl::GLenum’ to ‘cl_GLenum {aka unsigned int}’ for argument ‘3’ 
to ‘_cl_mem* clCreateFromGLTexture(cl_context, cl_mem_flags, cl_GLenum, cl_GLint, cl_GLuint, cl_int*)’
```

Any work around you guys can think of that is scalable for other similar GLenums used by OpenCL header is appreciated.

Thank you.

**Comment by scheibel** [comment]
A simple solution would be an explicit static cast: ```static_cast<cl_GLenum>(texture_target)```

But I think a more sophisticated solution would be to provide and use a type-safe OpenCL API as well.

**Comment by 9prady9** [comment]
Alternative (1) would require us to do modifications to `cl.hpp` provided by Khronos and every user who will use [our library](https://github.com/arrayfire/forge) will have use this modified version of cl.hpp header explicitly for all their OpenCL-GL interop applications.

Alternative (3) would require the least code changes from our perspective. How do i use these non-type-safe headers if they are already available ? Will there be any down sides to using this version of headers other than type safety ?

Alternative (2) is more safer approach in my opinion too, but i am not sure how much of effort is that and who would be in better position to implement such type-safe CL-GL API. Any thoughts on that ?

**Comment by scheibel** [comment]
I just had a quick look into the OpenCL API specification at https://github.com/KhronosGroup/OpenCL-Docs/blob/master/xml/cl.xml. It seems quite similar to the ones for OpenGL, if not even equal in structure and semantics.

I opened a ticket in our generator project to handle this feature request there: https://github.com/cginternals/khrbinding-generator/issues/23
