### ISSUE TITLE
Where is glbinding_api.h ?

### ISSUE THREAD

**Issue by akatray** [cginternals/glbinding#177]
Not in release.

**Comment by scheibel** [comment]
I'm not sure what the *release* is for you. We structured glbinding into components (using cmake semantics) and the ```glbinding_api.h``` header file is in the dev component. However, this header file is not included in the git repository as it is generated during cmake project configuration.
If you have just the runtime component installed then you have no header files, just the runtime libraries.

If you take a look at the ```glbinding-2.0.0-msvc2015-x64-dev.zip``` archive (https://github.com/cginternals/glbinding/releases) you can find the header file in ```include/glbinding/glbinding_api.h```.

I hope this helps.

**Comment by akatray** [comment]
I downloaded source one. Will grab it from dev. Thanks.
