### ISSUE TITLE
releaseContext(ctx) wipes out functions on contexts other than ctx

### ISSUE THREAD

**Issue by marcojez** [cginternals/glbinding#198]
I'm experiencing crashes at the call site of GL functions after releaseContext() has been called in another thread for some other context. It seems that the neglectState() function corrupts the internal data structure when the context being released is the last one (pos == maxpos). Please see AbstractFunction.cpp, line 91:

const auto size = static_caststd::size_t(std::max(0, **pos - 1**));

I believe that **pos - 1** should actually be just **pos**:

const auto size = static_caststd::size_t(std::max(0, pos));

This is the first time I look into the glbinding code, so I might be missing something. Can someone verify please?

Cheers,
Marco

**Comment by cgcostume** [comment]
@scheibel i suggest to add test(s) for this

**Comment by cstoitner** [comment]
This problems seems to still exist in 3.0.2.

**Comment by scheibel** [comment]
Thanks for reconfirming.

**Comment by cy20lin** [comment]
Recently I still encounter this issue on glbinding v3.1, the `std::out_of_range` is thrown while using the gl APIs after the other context is released by `releaseContext(ctx)`. 

The issue is reproduced with the test #324.

**Comment by scheibel** [comment]
I pushed a workaround. The management of released contexts needs an actual overhaul as it was only effective if the last context was released.
