### ISSUE TITLE
Multiple Context Example

### ISSUE THREAD

**Issue by kestrelm** [cginternals/glbinding#199]
Hello,

I couldn't seem to find an example for multiple contexts in here:
https://github.com/cginternals/glbinding/tree/master/source/examples

Is there something I am missing or can you point me to an example with multiple contexts?

Thanks

**Comment by scheibel** [comment]
If you just search code that uses multiple contexts you may use our [multi-context-test](https://github.com/cginternals/glbinding/blob/master/source/tests/glbinding-test/MultiContext_test.cpp) as reference. But in a sense you're right, an actual multi-context example is missing.

**Comment by jep-dev** [comment]
Hey, just leaving a friendly reminder - the front page links to a missing blob instead.

https://github.com/cginternals/glbinding/blob

Keep up the good work (honestly.)
