### ISSUE TITLE
Static Linking

### ISSUE THREAD

**Issue by TrygveSkogsholm** [cginternals/glbinding#207]
I wanted to static link glbinding. I cloned the repo, changed the project type of glbinding to static library (including changing from dll to .lib).

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) void __cdecl gl::glBegin(enum gl::GLenum)" (__imp_?glBegin@gl@@YAXW4GLenum@1@@Z) referenced in function ...
```

This is not just a matter of it not finding glbinding.lib as it explicitly complains about not finding it if it is missing. I am fairly certain I am matching the correct configuration and platform from the glbinding solution created by CMake.

What else do I need to do?

**Comment by scheibel** [comment]
Which compiler do you use?
It seems like an MSVC on Windows.

Typically, this error indicates that this symbol is not found in any library linked into the binary.
The import declaration looks correct (```__declspec(dllimport)``` and the signature is also correct.
Is this the only function with linker error (are there any other OpenGL functions that can be successfully resolved) or are there more similar errors and you shortened the error log?

**Comment by sbusch42** [comment]
The preprocessor definition GLBINDING_STATIC_DEFINE must be defined in your project that uses glbinding as a static library. That should get rid of the declspec(dllimport) in the include header.
When you use the exported target of our cmake script, this is taken care of automatically. However, if you just add the library name to your linker, you need to specify the GLBINDING_STATIC_DEFINE definition as well (-DGLBINDING_STATIC_DEFINE)

**Comment by scheibel** [comment]
Yeah, I totally missed that the dllimport should only exist if you want to link dynamically.

**Comment by TrygveSkogsholm** [comment]
@scheibel Yeah I shortened the log, it was pretty much everything in the gl namespace.
@sbusch42 GLBINDING_STATIC_DEFINE made it happy, some exceptions are floating around because this is the first time using glbinding to render but it is indeed rendering. Thank you very much, I'll try to color inside the lines from now on.
