### ISSUE TITLE
Enable multi OS build for mac os using travis ci.

### ISSUE THREAD

**Issue by cgcostume** [cginternals/glbinding#210]
https://docs.travis-ci.com/user/multi-os/

The current travis configuration only covers gcc on linux. A second configuration building on os x using clang must be added. The current reference to the os x jenkins build must be removed.

**Comment by scheibel** [comment]
Travis now build glbinding on both Ubuntu and macOS.
Url: https://travis-ci.org/cginternals/glbinding
