### ISSUE TITLE
Getting error with "gl.h"

### ISSUE THREAD

**Issue by acterhd** [cginternals/glbinding#211]
I getting error with glbindings. Builded from source under Windows. This error in my project, in compilation stage. 
```
#error:  "glbinding is not compatible with gl.h"	phantom-test	C:\glsl-tools\build\include\glbinding\nogl.h	3	
```

Also, I have another error, if include before: 

```
    typedef GLenum enumv;
    enum class Type : enumv {
        Float = GL_FLOAT,
        Double = GL_DOUBLE,
        Int = GL_INT,
        UnsignedInt = GL_UNSIGNED_INT,
        Int64 = GL_INT64_ARB,
        UnsignedInt64 = GL_UNSIGNED_INT64_ARB,
        Byte = GL_BYTE,
        UnsignedByte = GL_UNSIGNED_BYTE,
        Short = GL_SHORT,
        UnsignedShort = GL_UNSIGNED_SHORT,
        HalfFloat = GL_HALF_FLOAT
        //TODO: VEC types
    };
```

Error are very recusrive. Should be int if enum, and should be enum if int. I don't know why?

**Comment by scheibel** [comment]
It seems as if you're using glbinding together with another project that provides the OpenGL API (here: gl.h). As we define most symbols as a different type and some projects even uses macros to define values (e.g., GL_TRUE), we are not compatible with such header files.

What you experience is our guard that warns you when glbinding suspect incompatibility with other OpenGL API header files.

Typically, we suggest separating the project structure (and if that would be an overkill, just the affected source file/s) into the ones with the glbinding dependency and the other ones.
YOu may want to have a look at our Qt example, where Qt comes with OpenGL API header files that shouldn't clash with ours (https://github.com/cginternals/glbinding/tree/master/source/examples/cubescape-qt):
* The viewer and canvas uses Qt and just classes of glbinding that doesn't use actual OpenGL types
* The painter is an actual rendering using the glbinding interfaces for OpenGL.

**Comment by scheibel** [comment]
Regarding your other error: If you actually use glbinding aand its types, then ```GLenum``` is actually an ```enum class``` and a.f.a.i.k., enum classes cannot be underlying types on enum classes.

Further, it seems as if you're trying to categorize the enum values by yourself. We also have such goal and we would be happy to provide such categories as part of glbinding (as we do with bit fields). However, we try to limit manual maintenance and fixing of the OpenGL API; so we currently wait for the gl.xml to support enum categrories is some time.

**Comment by acterhd** [comment]
I had error that can't been fixed: bitfields. glbinding can't recategorize bitfields :(

**Comment by scheibel** [comment]
If you mean the bitfield group we call ```BufferStorageMask```, this is an enum class with underlying type int; see ```glbinding/gl/bitfield.h```:
```cpp
enum class BufferStorageMask : unsigned int
{
    GL_NONE_BIT                                = 0x0, // Generic GL_NONE_BIT
    GL_MAP_READ_BIT                            = 0x0001, // reuse from BufferAccessMask
    GL_MAP_WRITE_BIT                           = 0x0002, // reuse from BufferAccessMask
    GL_MAP_PERSISTENT_BIT                      = 0x0040, // reuse from BufferAccessMask
    GL_MAP_COHERENT_BIT                        = 0x0080, // reuse from BufferAccessMask
    GL_DYNAMIC_STORAGE_BIT                     = 0x0100,
    GL_CLIENT_STORAGE_BIT                      = 0x0200,
};
```

Further, I'm still not sure how you want to use GLbitfields and GLenums in one operation. Can you provide example code? Do you want to extend the bitfield values with own values?

**Comment by acterhd** [comment]
Wait... I prepare my wrapper example. I at this time used GLAD, I try reuse
glbindings again.

**Comment by acterhd** [comment]
Okay, first issue I fixed, but I got another problem... 
Functions require defined by glbindings types (i.e. masks, bitfields).

**Comment by scheibel** [comment]
I presume the original problem is solved. For different, emerging errors I suggest to open a new ticket.
