### ISSUE TITLE
glbinding incompatible with CUDA and CMake

### ISSUE THREAD

**Issue by acterhd** [cginternals/glbinding#212]
I tried to load glbinding in my CUDA Cmake project, but visual studio said that "glbinding.lib not found". BUT! I did all true! Even glbinding directory correct. 

```Cmake
cmake_minimum_required (VERSION 3.0)
project (opengl-tracer)

set (PROJECT_NAME opengl-tracer)
set (DEP_DIR "${CMAKE_MODULE_PATH}")
set (LIB_DIR "${DEP_DIR}/lib")
set (INC_DIR "${DEP_DIR}/include")
set (CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH};${PROJECT_SOURCE_DIR}/modules/")

find_package(OPENGL REQUIRED)
find_package(GLFW REQUIRED)
find_package(CUDA REQUIRED)
find_package(GLBINDING REQUIRED)

set (LIBS ${GLFW_LIBRARIES} ${OPENGL_LIBRARIS} ${GLBINDING_LIBRARIES})
set (CMAKE_CXX_FLAGS " /Ox /Ot /Ob2 /Oi ")
set (CMAKE_CXX_STANDARD_REQUIRED ON)
set (CMAKE_CXX_STANDARD 14)
set (CMAKE_CXX_EXTENSIONS ON)

set(
    CUDA_NVCC_FLAGS
    ${CUDA_NVCC_FLAGS}
    -arch=sm_50
)

set(rincludes_list 
    "./include/*.hpp"
    "./include/*.cpp"
    "./include/lodepng/*.h"
    "./include/lodepng/*.c"
    "./include/lodepng/*.hpp"
    "./include/lodepng/*.cpp"
    "./include/*.cc"
    "./include/phantom/*.hpp"
    "./include/phantom/opengl/*.hpp"
    "./include/phantom/utils/*.hpp"
    "./include/tiny_obj_loader/*.h"
    "./include/tiny_obj_loader/*.cc"
    "./shaders-sdk/include/*"
    "./shaders-sdk/render/*"
    "./shaders-sdk/voxelizer/*"
    "./shaders-sdk/voxelizer-2/*"
)
file (GLOB rincludes RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} ${rincludes_list})

add_compile_options(-std=c++14)
cuda_add_executable(${PROJECT_NAME} main.cu ${rincludes})
link_directories(${LIB_DIR};${GLFW_LIBRARY_DIRS};${OpenGL_LIBRARY_DIRS};${GLBINDING_LIBRARY_DIRS})
target_link_libraries(${PROJECT_NAME} ${LIBS})
include_directories("${INC_DIR};${PROJECT_SOURCE_DIR};${PROJECT_SOURCE_DIR}/include;${GLFW_INCLUDE_DIR};${GLFW_INCLUDE_DIR};${GLBINDING_INCLUDE_DIR}")

foreach(source IN LISTS rincludes)
    get_filename_component(source_path "${source}" PATH)
    string(REPLACE "/" "\\" source_path_msvc "${source_path}")
    source_group("${source_path_msvc}" FILES "${source}")
endforeach()
```

So, I can say that CUDA, Cmake and glbinding incompatible with these projects. 

Also, may require "obj" library.

**Comment by scheibel** [comment]
Our current glbinding find script doesn't provide ```${GLBINDING_LIBRARIES}``` and ```${GLBINDING_INCLUDE_DIRS}``` anymore, we rely on current CMake interfaces where you can use ```glbinding::glbinding``` as library target for your ```target_link_libraries``` call.
Example:
```target_link_libraries(${PROJECT_NAME} ${LIBS} glbinding::glbinding)```
Using this method, the include directories are also set with this one call.

**Comment by acterhd** [comment]
I found issues with compatibility. If declare "using namespace gl;" most types become ambigous.

**Comment by scheibel** [comment]
Thanks for amending incompatible use cases between glbinding and other APIs, but we're currently working on other aspects of our ecosystem. So, please, don't expect any progress on this in the next weeks.

However, I think the ambiguous types doesn't occur inside of glbinding but between glbinding and another API (e.g., CUDA) as they define some symbols of the OpenGL API themselves. As we, by design, provide a full OpenGL API with glbinding I don't think we can solve this issue within glbinding. Probably, the downstream projects have to get patched.

**Comment by acterhd** [comment]
I found problems with compatibility with GLFW.

**Comment by scheibel** [comment]
We have examples where we use glbinding in combination with GLFW (e.g., https://github.com/cginternals/glbinding/tree/master/source/examples/cubescape). The required trick is to tell GLFW to not include the own OpenGL headers. Therefore, you have to define ```GLFW_INCLUDE_NONE``` while compiling your source code containing both glbinding and GLFW code.

**Comment by acterhd** [comment]
Oh.... I have too many problems of compatibility with `PhantomGL`. 
1. Bitfields cannot be re-enumed and reused by functions who using it. Need write separate functions for glbindings, and directly with `GL_`, because (again) bitfields cannot be renamed. But will problematic documentate that "BarrierFlags::All" in reality - "GL_BARRIER_ALL". 
2. Enums also not compatible with radix sort of `phantom-tracer`. Against need write separate library that compatible with glbindings.

**Comment by scheibel** [comment]
The goal of glbinding is the provision of the OpenGL API using less error-prone constructs. That implies that we try to stick to the official API as close as possible. Your suggestions seems like reinterpretations of the API towards more readable or more comprehensible symbol names. We will not provide such features in glbinding and suggest to use glbinding as plain OpenGL interface and adding own abstraction layers on top (e.g., in form of engines).
