### ISSUE TITLE
glbinding macports portfile (and one for cpplocate)

### ISSUE THREAD

**Issue by kencu** [cginternals/glbinding#215]
Hi. I came across glbinding via Widelands, and wrote up a macports portfile that installs the current version very nicely. Also, another for cpplocate, to support building the examples. These portfiles have been submitted to macports, and are waiting for formal incorporation. 

But anyone who needs them now for development could used them. They are here:
<https://github.com/kencu/myports/tree/master/devel/glbinding> and <https://github.com/kencu/myports/tree/master/devel/cpplocate>. You can download the files and use macports to install these libraries and tools. If you need any help doing this, just ask and I'll explain more. 

Soon they will be available in macports directly I hope, and you can use them in your applications and macports will install the libraries automatically.

In both cases I had to patch CMakeLists.txt to explicitly set (SYSTEM_DIR_INSTALL TRUE) as the file layout exploring logic didn't work correctly for MacPorts file layout. Perhaps there is a way it could be enhanced to support MacPorts without patching...always better.

Thanks!

**Comment by kencu** [comment]
The MacPorts devs had an issue with the location the default installed location of the cmake files; these were considered to be non-standard, and that was the main reason that this submission has been rejected by macports to date. However, when I change these to the locations they preferred, they don't work correctly. They very helpfully rewrote the cmake scripts, which you can see here <https://trac.macports.org/ticket/52927> but I don't know if that meets with your plans. So I suppose that makes macports a no-go at present, unless something changes.

**Comment by scheibel** [comment]
Unfortunately, the integration with macports seems stale.

Regarding your `SYSTEM_DIR_INSTALL` issue:
It seems as if you want another directory that we could easily add to the list of tested paths. Which is it?

**Comment by kencu** [comment]
I think you can close this. The above is indeed very stale now.

If someone would like glbinding in MacPorts they can start afresh, as much has changed both here and in MacPorts.
