### ISSUE TITLE
Missing enum GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS

### ISSUE THREAD

**Issue by lighthouse3d** [cginternals/glbinding#216]
Hi, 

It seems that you're missing this enum: GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS

Adding it to enums.h does work.

Best Regards,

Antonio

**Comment by scheibel** [comment]
It seems like this constant is only defined for OpenGL ES and OpenGL SC, not plain OpenGL. However, the constant ```GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_EXT``` is defined for OpenGL and can be found in the full enum header for glbinding (```glbinding/gl/enum.h```) and in the version-specific enum extension headers (e.g., ```glbinding/gl45ext/enum.h```). Fortunately, this enum (and its EXT variant) has the same numerical value across all APIs, so you can provide own abstractions if you need them.

Concluding: it doesn't seem as if the provided gl.xml is wrong and thus, we won't integrate it as a patch.

**Comment by lighthouse3d** [comment]
Yes, you're absolutely right. Thanks, and sorry for wasting your time.

Best Regards,

Antonio
