### ISSUE TITLE
CMake errors with glbinding as subproject

### ISSUE THREAD

**Issue by bigdavedev** [cginternals/glbinding#217]
I am trying to use glbinding in my project as a dependency. I want to build it along-side my project instead of installing it to my system. Trouble is, I cannot get CMake to generate the Makefiles. I am met with the following output:

    Configuring glbinding
    CMake Error at build/external/glbinding/CMakeFiles/git-data/grabRef.cmake:36 (file):
      file failed to open for reading (No such file or directory):
    
        /home/dabr/git/github.com/bigdavedev/opengl/build/external/glbinding/CMakeFiles/git-data/head-ref
    Call Stack (most recent call first):
      external/glbinding/cmake/GetGitRevisionDescription.cmake:79 (include)
      external/glbinding/CMakeLists.txt:32 (get_git_head_revision)
    
    
    -- Found OpenGL: /usr/lib64/libGL.so  
    -- Lib glbinding
    -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
    -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
    -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
    -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
    -- Performing Test COMPILER_HAS_DEPRECATED_ATTR
    -- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
    -- Could NOT find GLFW (missing:  GLFW_LIBRARIES GLFW_INCLUDE_DIR) 
    Tool glcontexts skipped: GLFW not found
    -- Could NOT find GLFW (missing:  GLFW_LIBRARIES GLFW_INCLUDE_DIR) 
    Tool glfunctions skipped: GLFW not found
    -- Could NOT find GLFW (missing:  GLFW_LIBRARIES GLFW_INCLUDE_DIR) 
    Tool glmeta skipped: GLFW not found
    -- Could NOT find GLFW (missing:  GLFW_LIBRARIES GLFW_INCLUDE_DIR) 
    Tool glqueries skipped: GLFW not found
    -- Command update
    -- Command generate
    -- Configuring incomplete, errors occurred!
    See also "/home/dabr/git/github.com/bigdavedev/opengl/build/CMakeFiles/CMakeOutput.log".
    See also "/home/dabr/git/github.com/bigdavedev/opengl/build/CMakeFiles/CMakeError.log".

My CMakeLists.txt looks like:

    cmake_minimum_required (VERSION 3.0 FATAL_ERROR)

    ## Dependencies
    set (BUILD_SHARED_LIBS   ON  CACHE BOOL "Use shared libraries for GLFW")
    set (GLFW_BUILD_EXAMPLES OFF CACHE BOOL "Don't need the examples")
    set (GLFW_BUILD_TESTS    OFF CACHE BOOL "Don't need to test")
    set (GLFW_BUILD_DOCS     OFF CACHE BOOL "Don't need the docs in the project")
    add_subdirectory (${CMAKE_SOURCE_DIR}/external/glfw)
    
    message ("Configuring glbinding")
    
    set (BUILD_SHARED_LIBS      OFF CACHE BOOL "Prefer static linkage for the bindings")
    set (OPTION_BUILD_EXAMPLES  OFF CACHE BOOL "Don't need the examples")
    set (OPTION_BUILD_TESTS     OFF CACHE BOOL "Don't need to test")
    set (OPTION_BUILD_GPU_TESTS OFF CACHE BOOL "Don't need to test")
    set (OPTION_BUILD_TOOLS     OFF CACHE BOOL "Don't need the tools")
    add_subdirectory (${CMAKE_SOURCE_DIR}/external/glbinding)
    
    set (META_PROJECT_NAME "opengl-demos")

Some other system information:

    uname -a: Linux ullr 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
    cmake --version: 3.7.1
    git --version: 2.11.0

The following patch allows CMake to generate everything as expected:

    diff --git a/cmake/GetGitRevisionDescription.cmake b/cmake/GetGitRevisionDescription.cmake
    index 72426cbf..f031b4b6 100644
    --- a/cmake/GetGitRevisionDescription.cmake
    +++ b/cmake/GetGitRevisionDescription.cmake
    @@ -76,7 +76,6 @@ function(get_git_head_revision _refspecvar _hashvar)
         configure_file("${_gitdescmoddir}/GetGitRevisionDescription.cmake.in"
             "${GIT_DATA}/grabRef.cmake"
             @ONLY)
    -    include("${GIT_DATA}/grabRef.cmake")
     
         set(${_refspecvar} "${HEAD_REF}" PARENT_SCOPE)
         set(${_hashvar} "${HEAD_HASH}" PARENT_SCOPE)

I don't feel like that is a solution, though. Have I missed something obvious?

/Dave

**Comment by scheibel** [comment]
It seems as if we have a bug in retrieving the git commit from which we generate a part of the glbinding version.

There may be a further issue:
With your setup, where you integrate glbinding into your own repository (I assume its also git?), the found commit hash would be of your repository and not of glbinding.

I think we need to re-discuss on when and how to retrieve and use the git commit hash.

**Comment by bigdavedev** [comment]
OK, that makes sense. I had a look at the generated grabRef.cmake and it is instead pointing to the super-project's git directory. For reference, I am using glbinding as a submodule.

The grabRef.cmake file looks as follows:

    # 
    # Internal file for GetGitRevisionDescription.cmake
    #
    # Requires CMake 2.6 or newer (uses the 'function' command)
    #
    # Original Author:
    # 2009-2010 Ryan Pavlik <rpavlik@iastate.edu> <abiryan@ryand.net>
    # http://academic.cleardefinition.com
    # Iowa State University HCI Graduate Program/VRAC
    #
    # Copyright Iowa State University 2009-2010.
    # Distributed under the Boost Software License, Version 1.0.
    # (See accompanying file LICENSE_1_0.txt or copy at
    # http://www.boost.org/LICENSE_1_0.txt)
    
    set(HEAD_HASH)
    
    file(READ "/home/dabr/git/github.com/bigdavedev/opengl/build/external/glbinding/CMakeFiles/git-data/HEAD" HEAD_CONTENTS LIMIT 1024)
    
    string(STRIP "${HEAD_CONTENTS}" HEAD_CONTENTS)
    if(HEAD_CONTENTS MATCHES "ref")
        # named branch
        string(REPLACE "ref: " "" HEAD_REF "${HEAD_CONTENTS}")
        if(EXISTS "/home/dabr/git/github.com/bigdavedev/opengl/.git/${HEAD_REF}")
            configure_file("/home/dabr/git/github.com/bigdavedev/opengl/.git/${HEAD_REF}" "/home/dabr/git/github.com/bigdavedev/opengl/build/external/glbinding/CMakeFiles/git-data/head-ref" COPYONLY)
        elseif(EXISTS "/home/dabr/git/github.com/bigdavedev/opengl/.git/logs/${HEAD_REF}")
            configure_file("/home/dabr/git/github.com/bigdavedev/opengl/.git/logs/${HEAD_REF}" "/home/dabr/git/github.com/bigdavedev/opengl/build/external/glbinding/CMakeFiles/git-data/head-ref" COPYONLY)
            set(HEAD_HASH "${HEAD_REF}")
        endif()
    else()
        # detached HEAD
        configure_file("/home/dabr/git/github.com/bigdavedev/opengl/.git/HEAD" "/home/dabr/git/github.com/bigdavedev/opengl/build/external/glbinding/CMakeFiles/git-data/head-ref" COPYONLY)
    endif()
    
    if(NOT HEAD_HASH)
        file(READ "/home/dabr/git/github.com/bigdavedev/opengl/build/external/glbinding/CMakeFiles/git-data/head-ref" HEAD_HASH LIMIT 1024)
        string(STRIP "${HEAD_HASH}" HEAD_HASH)
    endif()

I see that the submodule case is covered in cmake/GetGitRevisionDescription.cmake however, it obtains the .git folder by setting the GIT_PARENT_DIR to CMAKE_SOURCE_DIR which for a submodule means that you will get the super-project directory. By using PROJECT_SOURCE_DIR you will get the last declared project's directory. Unfortunately, glbinding declares the project _after_ trying to work out the commit hash. I moved the project declaration above that call and everything worked. Here is the diff:

    diff --git a/CMakeLists.txt b/CMakeLists.txt
    index 7f6bb7fd..34611f89 100644
    --- a/CMakeLists.txt
    +++ b/CMakeLists.txt
    @@ -27,6 +27,8 @@ set_policy(CMP0063 NEW) # ENABLE CMP0063: Honor visibility properties for all ta
     # 
     # Project description and (meta) information
     # 
    +# Declare project
    +project(${META_PROJECT_NAME} C CXX)
     
     # Get git revision
     get_git_head_revision(GIT_REFSPEC GIT_SHA1)
    @@ -67,8 +69,6 @@ option(OPTION_BUILD_EXAMPLES  "Build examples."
     set_property(GLOBAL PROPERTY USE_FOLDERS ON)
     set(IDE_FOLDER "")  
     
    -# Declare project
    -project(${META_PROJECT_NAME} C CXX)
     
Obviously moving the project declaration like that is not ideal, so that is something I will let you sort yourself. But this is likely the best solution.
     # Set output directories
     set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR})
    diff --git a/cmake/GetGitRevisionDescription.cmake b/cmake/GetGitRevisionDescription.cmake
    index 72426cbf..4a126d46 100644
    --- a/cmake/GetGitRevisionDescription.cmake
    +++ b/cmake/GetGitRevisionDescription.cmake
    @@ -40,7 +40,7 @@ set(__get_git_revision_description YES)
     get_filename_component(_gitdescmoddir ${CMAKE_CURRENT_LIST_FILE} PATH)
     
     function(get_git_head_revision _refspecvar _hashvar)
    -    set(GIT_PARENT_DIR "${CMAKE_SOURCE_DIR}")
    +    set(GIT_PARENT_DIR "${PROJECT_SOURCE_DIR}")
         
         if(NOT EXISTS "${GIT_PARENT_DIR}/.git")
             # .git dir not found

**Comment by scheibel** [comment]
I fixed the master branch and tested a similar setup to yours.
I used the following snippet to integrate ```glbinding``` directly into the outer build:
```cmake
set(META_PROJECT_NAME "glbinding")
add_subdirectory(glbinding/source/glbinding)
```
**Please note that we don't recommend using such direct integration.**

Instead, we provide cmake find scripts (```glbinding-config.cmake```) that are aware of build directories as source of the library so there is no need to install glbinding into your system. Before calling cmake, you can adjust your ```CMAKE_PREFIX_PATH``` to point to the glbinding source directory (current best-practice of cmake) or set the ```glbinding_DIR``` environment variable instead. Then we assume that there is a ```build``` directory where the release build (or both for Windows MSVC) can be found and/or a ```build-debug``` directory where the debug build can be found.
