### ISSUE TITLE
Emscripten support

### ISSUE THREAD

**Issue by swaption** [cginternals/glbinding#219]
I think it should be possible to using glbinding with Emscripten's OpenGL support [1], though I'm not sure which project needs to implement the support? I do know that Emscripten implements its own emulations of GLEW, GLU, GLUT, GLFW, etc. [2]

Please see:
- [1] https://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/OpenGL-support.html
- [2] https://github.com/kripken/emscripten/tree/master/system/include/GL

**Comment by scheibel** [comment]
Having glbinding in emscripten sounds nice. However, we need to investigate if emscripten supports C++ libraries besides the stdlib.

Another solution could be that glbinding uses another OpenGL binding as GLEW instead of own pointer resolution which would limit the features of glbinding to the additional type-safety and the superimposed interfaces.

**Comment by swaption** [comment]
Hi @scheibel 

> we need to investigate if emscripten supports C++ libraries besides the stdlib

emscripten has support for the following "system" libraries : https://github.com/kripken/emscripten/tree/incoming/system/include

It also has official ports of the following additional libraries: https://github.com/emscripten-ports

I don't know if that helps...

**Comment by scheibel** [comment]
Thanks for participating. I actually had a look at the ```system/include``` folder yesterday and your second link seems like a good starting point for learning how to provide a glbinding-port for emscripten.

**Comment by scheibel** [comment]
In the meantime, we actually use glbinding in emscripten builds.
What were currently working on is a further restriction of the exposed OpenGL functions to better match the available WebGL functionality. This will be discussed further in our generator project:
- https://github.com/cginternals/khrbinding-generator/issues/7
- https://github.com/cginternals/khrbinding-generator/issues/18

Closing this issue for now.

**Comment by kalankaboom** [comment]
Hello!
Could you point me in the direction of an example using emscripten?
I am trying to build a project of mine but I am running into errors I cannot seem to solve.
