### ISSUE TITLE
Review MacPorts integration

### ISSUE THREAD

**Issue by scheibel** [cginternals/glbinding#221]
It seems like glbinding is available using MacPorts (https://trac.macports.org/ticket/52910).

Tasks:
 * Review if installing glbinding via MacPorts works as expected
 * Reverse engineer process and artifacts required steps for a MacPorts integration, integrate findings into https://github.com/cginternals/cmake-init/issues/43

**Comment by kencu** [comment]
see PR #215 as well.

**Comment by michaelld** [comment]
So what y'all need to concentrate on are: (1) installing cmake files into hopefully an externally-specifiable directory; and (2) the *-config.cmake file working for (a) the target itself; (b) in-tree targets (for example, test-cpplocate); and (c) out-of-tree targets (for example: glbinding, when using cpplocate). I just attached updates that fix the *-config.cmake to search a little more robustly ... but, allowing some externally-specifiable directory would be even better.

**Comment by scheibel** [comment]
Closing this for now, as the integration to macports seems stale.
