### ISSUE TITLE
[RFC] Make SharedBitfield usable in a constexpr context

### ISSUE THREAD

**Issue by cinghiale** [cginternals/glbinding#228]
I need to use a SharedBitfield in a constexpr context because I want to pass the result of oring two flags to a template parameter; something like this

```cpp
template<GLbitfield> void f();

constexpr auto flags = static_cast<GLbitfield>(GL_MAP_WRITE_BIT | GL_MAP_READ_BIT);
foo<flags>();
```

In order for the above code to work I have created this incomplete [patch](https://gist.github.com/cinghiale/b5a2004362ee8e598385a6e58f750f77) (made against glbinging 2.1.1, as shipped by Ubuntu 16.10)

It's incomplete (only limited to the constructors and operator|) but purely mechanical

If you like the idea, I can work on a PR that covers the full class

IIUC such PR should affects:
 - glbinding/SharedBitfield.*
 - codegeneration/scripts/templates/bitfield.h.tpl

**Comment by scheibel** [comment]
This sounds interesting. I added the ```GLBINDING_CONSTEXPR``` in the ```glbinding/glbinding_features.h``` header that should be used instead of a plain ```constexpr``` for compilers not supporting this keyword in all required contexts (e.g., MSVC 2013 cannot handle constexpr member functions).

**Comment by scheibel** [comment]
I created the PR #231 for this, maybe you want to test?

**Comment by cinghiale** [comment]
Thank you! I will give it a try in the next days!

**Comment by scheibel** [comment]
I merged this into master. If any error occurs while testing, please open a new issue.
