### ISSUE TITLE
GL_VERTEX_ARRAY enum isn't in the gl45core namespace even if it should be

### ISSUE THREAD

**Issue by GuildMasterInfinite** [cginternals/glbinding#229]
I wanted to use only OpenGL 4.5 Core functions & enums, so I use
```c++
using namespace gl45core;
```
before my code.

I tried to use [glObjectLabel](https://www.khronos.org/opengl/wiki/GLAPI/glObjectLabel) to ease debugging, which is in OpenGL core since 4.3.

Using it with vertex buffers works well:
```c++
glObjectLabel(GL_BUFFER, someBuffer, 0, nullptr);
```
as the GL_BUFFER enum is in the `gl45core` namespace.

However, this fails to compile with vertex arrays:
```c++
glObjectLabel(GL_VERTEX_ARRAY, someVertexArray, 0, nullptr);
```
because GLBinding doesn't consider the enum GL_VERTEX_ARRAY to be in OpenGL 4.5 Core.

Using `gl::GL_VERTEX_ARRAY` or `GLenum::GL_VERTEX_ARRAY` works.

This is a test snippet to show what the problem is:
```c++
void test()
{
	using namespace gl45core;

	GLuint someBuffer = 0, someVertexArray = 0;

        // This compiles as-is.
	glObjectLabel(GL_BUFFER, someBuffer, 0, nullptr);

	// This fails to compile:
	glObjectLabel(GL_VERTEX_ARRAY, someVertexArray, 0, nullptr);

        // This compiles.
	glObjectLabel(gl::GL_VERTEX_ARRAY, someVertexArray, 0, nullptr);
}
```

**Comment by scheibel** [comment]
Thanks for reporting.
It seems like the example you provide is valid OpenGL.
Source: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glObjectLabel.xhtml

However, ```GL_VERTEX_ARRAY``` was originally used with ```glEnableClientState``` which was deprecated with OpenGL 3.x and all associated constants were removed afterwards.
The enum ```GL_VERTEX_ARRAY``` was reintegrated through the ```KHR_debug``` extension.
As far as I can remember, this extension is not part of OpenGL 4.5 core, so the enum value can be found in the ext header [```gl45ext/enum.h```](https://github.com/cginternals/glbinding/blob/master/source/glbinding/include/glbinding/gl45ext/enum.h#L882).

**Comment by GuildMasterInfinite** [comment]
Thanks for replying. However, as far as I can understand, the enum should be in the core namespace.

> As far as I can remember, this extension is not part of OpenGL 4.5 core

According to the [OpenGL wiki page on this feature (debug output)](https://www.khronos.org/opengl/wiki/Debug_Output): 

> Note that this feature, **which is core in 4.3**, has functionality that is generally exposed by two different extensions. The KHR extension is the **core feature**, which is always advertised when available.

(emphasis mine)

The [KHR_debug](https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_debug.txt) extension you mention, which _is_ in Core OpenGL since 4.3, does specify the GL_VERTEX_ARRAY enum.

I've also checked the [official OpenGL 4.5 Core specification](https://khronos.org/registry/OpenGL/specs/gl/glspec45.core.pdf), and found this feature in it (page 533):

> Table 20.4: Object namespace identifiers and the corresponding object types.
> ...
> TRANSFORM_FEEDBACK transform feedback
> VERTEX_ARRAY vertex array

So, I do believe that the `GL_VERTEX_ARRAY` should be also included in the `gl45core` namespace.

**Comment by scheibel** [comment]
We'll check if we patch the gl.xml (e.g., through adding KHR_debug to core as of 4.3) and if any more enum values are affected.

**Comment by GuildMasterInfinite** [comment]
Thanks! It's good to hear it will be fixed. I will close this issue when gl.xml gets patched.

**Comment by scheibel** [comment]
We actually didn't have to patch the gl.xml; it correct.
However, I patched our parser which didn't handle reintegrated symbols (one deprecated and removed, later readded for other use) until now (https://github.com/cginternals/glbinding/commit/77e1351341fd8ce97b9503fdb419a2fa05c2fd4c).

**Comment by scheibel** [comment]
I assume this issue is solved so I'm closing this issue for now.
If your problem stills remains using the current master, please reopen this issue.

**Comment by GuildMasterInfinite** [comment]
Yep, it's fixed, I rebuilt glbinding from master and now it works. Sorry I forgot to reply.
