### ISSUE TITLE
Wrong versioning in 2.1.2 release 

### ISSUE THREAD

**Issue by thfabian** [cginternals/glbinding#233]
The 2.1.2 release (and the current master) still contain the versioning for 2.1.1.
```CMake
set(META_VERSION_MAJOR       "2")
set(META_VERSION_MINOR       "1")
set(META_VERSION_PATCH       "1")
```

**Comment by scheibel** [comment]
Thanks for reporting. Unfortunately, strict release management prevents us from fixing this for the 2.1.1 release but I will release 2.1.3 with the correct versioning in the `CMakeLists.txt`.
