### ISSUE TITLE
Improvement - better type checks for Clang compiler

### ISSUE THREAD

**Issue by sergey-shambir** [cginternals/glbinding#236]
Clang compiler allows to specify function attributes to enforce warnings for functions with opaque pointers `const void*`.

Attributes are non-intrusive and can be placed in separate header.
Here is simple prototype for OpenGL: https://github.com/sergey-shambir/clang_opegl_typesafety/blob/master/opengl_typechecks.h

Imagine there is a wrong code:

```cpp
#include <GL/gl.h>
#include "opengl_typechecks.h"

const float normales = { 0, 0, 1 };
glNormalPointer(GL_DOUBLE, 0, normales );
```

After including `opengl_typechecks.h` and compiling with clang you get following warning:

```cpp
AppDelegate.cpp:122: warning: argument type 'const double *' doesn't match specified 'opengl' type tag that requires 'const float *' [-Wtype-safety]
    glNormalPointer(GL_FLOAT, 0, m_normales.front());
                    ~~~~~~~~     ^~~~~~~~~~~~~~~~~~
```

See also docs: https://clang.llvm.org/docs/AttributeReference.html#type-safety-checking

**Comment by scheibel** [comment]
This seems like a quite interesting feature. We'll investigate how we may integrate this into glbinding.
Your example shows an integration with a C interface using macros but I think we'll be able to use the same type tags.

However, we should research if such concept is more cross-compiler available. Leveraging features of a special compiler to increase reliability of an implementation seems nice, but I don't want to suggest that glbinding should be used primarily with clang.

**Comment by NicolBolas** [comment]
I do not think that this feature would be useful for this particular case. Consider something as simple as this:

```
vec3 arr[] = {{1, 0, 0}, {0, 1, 0}};
glNormalPointer(GL_FLOAT, sizeof(vec3), arr);
```

That would probably fail to compile under your code. But it shouldn't. It's still providing an array; it's just providing an array in a very different way.

And how would buffer objects work with this type checking? You're passing integer values, cast to pointers, not actual `float*`s. Wouldn't the type checker say no to that?

**Comment by scheibel** [comment]
We suggest that those type checks are added at a higher-level API. Closing this for now.
