### ISSUE TITLE
refine option defaults

### ISSUE THREAD

**Issue by cgcostume** [cginternals/glbinding#245]
| current name | current default | target name | target default |
| --------------- | ---------------- | ------------- | --------------- |
| `SELF_CONTAINED` | `OFF` | `SELF_CONTAINED` | `OFF` |
| `BUILD_TESTS` | `ON` | `BUILD_TESTS` | `OFF` |
| `BUILD_GPU_TESTS` | `ON` | `BUILD_TESTS` | `OFF` |
| `BUILD_DOCS` | `OFF` | `BUILD_DOCS` | `OFF` |
| `BUILD_TOOLS` | `ON` | - | always on |
| `BUILD_EXAMPLES` | `ON` | `BUILD_EXAMPLES` | `ON` |
| `BUILD_WITH_BOOST_THREAD` | `OFF` | `BUILD_WITH_BOOST_THREAD` | `OFF` |
|  |  | `BUILD_CHECK` | `OFF` |

If tests is enabled, gpu requiring tests are build only when gpu was detected (how to?).
If examples are enabled, examples that require missing 3rdp such as glew or qt are skipped.

**Comment by scheibel** [comment]
Requiring the tools to be always enabled will render GLFW a required dependency. I do not advise this.
