### ISSUE TITLE
glbinding::Binding::initialize() does not exist any longer --- how should glbinding be initialized?

### ISSUE THREAD

**Issue by Kuxe** [cginternals/glbinding#260]
With 5771ad8858675f06ec5b259ee40e98eff40b8b23, the signature `static void initialize(bool resolveFunctions = true);` was removed and replaced by `static void initialize(GetProcAddress functionPointerResolver, bool resolveFunctions = true);` which renders a [basic example](https://github.com/cginternals/glbinding#basic-example) in README.md obsolete.

Could anyone provide a compilable example of (or explain) how glbinding should be initialized post 5771ad8858675f06ec5b259ee40e98eff40b8b23? Thank you.

**Comment by sbusch42** [comment]
There are working examples within glbinding. You just need to enable them (-DOPTION_BUILD_EXAMPLES:BOOL=ON).

**Comment by sbusch42** [comment]
For example have a look here (when using GLFW):
https://github.com/cginternals/glbinding/blob/9f1dc54f80f0aef76be433eb97ea22da63ec2670/source/examples/cubescape/main.cpp#L104

Or here (when using Qt):
https://github.com/cginternals/glbinding/blob/9f1dc54f80f0aef76be433eb97ea22da63ec2670/source/examples/cubescape-qt/Canvas.cpp#L90

**Comment by Kuxe** [comment]
Thank you very much! The example provided in cubescape is up to date and answers my question. Closing.
