### ISSUE TITLE
Multi-Context support broken

### ISSUE THREAD

**Issue by j-o** [cginternals/glbinding#265]
Calling `glbinding::initialize` from two different contexts will try to register the default context handle 0 twice, in which case the second init is silently ignored.

**Comment by j-o** [comment]
Same thing for globjects

**Comment by scheibel** [comment]
Are you referring to the example for multi-context support, the README.md entry or the feature in general?

**Comment by j-o** [comment]
The feature in general. There is the workaround to call `Binding::initialize` directly, but this is rather obscure and not reflected in the README.

**Comment by scheibel** [comment]
I'll have a look at it.
