### ISSUE TITLE
Cannot compile, glbinding_api.h and glbinding_features.h are both missing.

### ISSUE THREAD

**Issue by AmadeusGaming** [cginternals/glbinding#269]
Hi,

I tried manually compiling this library in Code::Blocks because I don't understand how makefiles work, so compiling it this way is easier for me.

I created a new C++ project and imported all the header and source files, in their appropriate folder locations, set up the compiler for C++11, and attempted to build the project as a static library.

Several files fail on these includes:
#include <glbinding/glbinding_api.h>
#include <glbinding/glbinding_features.h>

Neither of these files exist anywhere. I do not know what to do about this.

Thanks in advance for any help you can provide.

**Comment by AmadeusGaming** [comment]
Nope, version 3.0 has the same problem.

**Comment by sbusch42** [comment]
These headers are generated files, which means they are created automatically during the build process. That is why they don't exist in the source tree. The build system we use is based on CMake. Please read up on how to use CMake, it's really not that hard. In short, you need to do these steps:
1. Install cmake
2. Create a build directory, invoke CMake to create the build inside that directory. You can instruct cmake to directly create a code::blocks project for you. See https://github.com/cginternals/glbinding/issues/269#issuecomment-423148654. You can also use a graphical frontend (cmake-gui).
3. Open the generated project in code::blocks and build the library.

**Comment by AmadeusGaming** [comment]
Alright, I'll see if I can figure out CMake, thanks.
