### ISSUE TITLE
khr-binding issues

### ISSUE THREAD

**Issue by cgcostume** [cginternals/glbinding#286]
related to the maintainability of glbinding:
- https://github.com/cginternals/khrbinding-generator/issues/15
- https://github.com/cginternals/khrbinding-generator/issues/14

**Comment by scheibel** [comment]
It seems like pystache has different outputs based on the system it is used on. We should stick to a native Linux (e.g., Ubuntu 18.04) as a short-term workaround. For a mid-term solution, we should switch to a more deterministic engine for template processing (https://github.com/cginternals/khrbinding-generator/issues/15).
