### ISSUE TITLE
glbinding-aux does not link on msvc 2019

### ISSUE THREAD

**Issue by cgcostume** [cginternals/glbinding#289]
waited several hours, did not crash nor finish ... msvc2019 is officially released and not in any beta/alpha state so i assume we should strive for support/fix as soon as possible.

**Comment by Zangetsu38** [comment]
i have same yes, and in debug is very quickely

**Comment by Zangetsu38** [comment]
Any developper have any idea for fix this, because is not probleme only for VS2019, but MS2017 have also issue for take 2 min for compile release build, and is not normal

**Comment by mcleary** [comment]
It links when building in debug mode. I tried disabling LTCG but still doesn't link in Release. Looks like a linker bug, to be honest.

**Comment by crackedmind** [comment]
It looks like MS fixed some linker bugs in 19.2 (released yesterday). glbinding-aux linked in 500 seconds on my machine,

**Comment by scheibel** [comment]
Thanks for the update. This is still some time but doable.

**Comment by crackedmind** [comment]
Another update.
With the latest MSVC 19.24.28314 (VS 2019 16.4.2) full rebuild tooks 120 secs.

**Comment by Zangetsu38** [comment]
120 sec is same with VS 2017

**Comment by cgcostume** [comment]
works fine now... compiler version:
```
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.26.28805.0
-- The CXX compiler identification is MSVC 19.26.28805.0
```

**Comment by stgatilov** [comment]
I'd like to comment that link-time code generation for static library on MSVC is quite rude, because this way every user of glbinding library has to compile and optimize the whole glbinding library every time he changes one cpp file in his own code.

I had to remove /GL and /Gw flags from cmake\CompileOptions.cmake to return link time back to normal.
