### ISSUE TITLE
default behavior when no `GetProcAddress` is provided

### ISSUE THREAD

**Issue by cgcostume** [cginternals/glbinding#290]
By default, glbinding should initialize with its own ProcAddress getter. The option to override glbinding's getter with another one, e.g., glew or glfw etc., should be optional, not mandatory.

We should make using glbinding as simple as possible by default.

**Comment by scheibel** [comment]
This would require additional dependencies (that are currently there, but not mandatory; see #203) that we ideally want to get rid of. But we may discuss this here.

**Comment by scheibel** [comment]
I added a PR where I re-added some of the older behavior. Using `LoadLibrary` and `dlopen` is re-added but the function pointer resolution using `wglGetProcAddress` and `glxGetProcAddress` is still omitted.
