### ISSUE TITLE
 cpplocate should be optional for examples (and tools)

### ISSUE THREAD

**Issue by cgcostume** [cginternals/glbinding#291]
if cpplocate cannot be found or is not provided, examples should fall back to a default implementation. I would prefer to not put the all-systems-every-deploy-scenario approach over convenience for most users: so i prefer to simplify building glbinding (all of it) out of the box as much as possible, i.e., make cpplocate optional and reduce dependencies as much as possible.

**Comment by scheibel** [comment]
The libraries and the tools should not be  dependent on cpplocate (and I hope it is this way). If we make the dependency to cpplocate optional for the examples, then we would have to hard-code a search-path (again). Maybe we want to investigate other solutions as resource-inlining as well.

**Comment by scheibel** [comment]
Implemented with 16d5d987bd65a6278066b3601b695b811fe943df.
