### ISSUE TITLE
GLboolean namespaces

### ISSUE THREAD

**Issue by dlyr** [cginternals/glbinding#301]
Hi, since my last update, I see that `GLboolean` is not in` gl45core` namespace for instance.
I do not check the previous behavior, but now, I see that `GLboolean` is only in `gl:: namespace`, while other GLtypes are imported in all namespace there are valid in.
So I had to change my reference to `GLboolean` to `gl::GLboolean`, or add `using namespace gl`, while for all other GLtypes I just add `using namespace gl45core`
i.e.
```
::.../glbinding/include/glbinding]$ find . -type f -name \*.h -exec grep -H GLboolean "{}" \; | grep using
./gl/boolean.h:using GLboolean = glbinding::Boolean8;
```
while 
```
::.../glbinding/include/glbinding]$ find . -type f -name \*.h -exec grep -H GLint "{}" \; | grep using
./gl42ext/types.h:using gl::GLint;
[...]
./gl44ext/types.h:using gl::GLint;
[...]
./gl10/types.h:using gl::GLint;
[...]
```

Is that new _feature_ on purpose ?
++

**Comment by scheibel** [comment]
This seems to be more of an accident. I'll check.
For reference, the following code should compile and work just fine:
```cpp
#include <glbinding/gl45core/boolean.h>

using namespace gl45core;

// ...

const gl45core::GLboolean b1 = gl45core::GL_TRUE;
const gl::GLboolean b2 = gl::GL_TRUE;
const GLboolean b3 = GL_TRUE;
```

**Comment by dlyr** [comment]
I confirm it do not compiles (see the referenced PR #305)
