### ISSUE TITLE
Conan packaging

### ISSUE THREAD

**Issue by kaidokert** [cginternals/glbinding#308]
I've just updated a Conan package to the [latest release here](https://github.com/kaidokert/conan-glbinding), based on [someone else's previous work](https://github.com/fishbupt/conan-glbinding). Now builds on both Travis/Appveyor and publishes to Bintray on push.

Any interest in getting this in here, or maybe to https://github.com/conan-io/conan-center-index ?

**Comment by Trass3r** [comment]
Why does it depend on glfw and why is it shared by default?

**Comment by kaidokert** [comment]
Fair questions both, I don't know, but i'll try clean it up.

**Comment by scheibel** [comment]
From the glbinding viewpoint, we use GLFW for the tools and examples; not the glbinding and glbinding-aux libraries theirselves.
And is the build default for conan shared or static libraries? We mostly use shared libraries within our setups.

**Comment by Trass3r** [comment]
At least it's the default for all relevant packages like glfw, sdl etc.

**Comment by dasmysh** [comment]
This may be a stupid question, but how can I use the conan package? I do not find it on any conan repositories.

**Comment by SpaceIm** [comment]
conan recipe of glbinding is now available in https://github.com/conan-io/conan-center-index

https://github.com/conan-io/conan-center-index/tree/master/recipes/glbinding/all

**Comment by scheibel** [comment]
Thanks for the effort, the integration, and the short usage example.
I added the information into the readme and I would close this issue at this point.

**Comment by kaidokert** [comment]
Whee, good to hear !
