### ISSUE TITLE
Consider enabling policy CMP0069 to allow link time optimization

### ISSUE THREAD

**Issue by tuankiet65** [cginternals/glbinding#313]
My project enables link time optimization by default for all targets using the `CMAKE_INTERPROCEDURAL_OPTIMIZATION` property. However glbinding does not honor this flag because the minimum CMake version that glbinding uses is 3.0, and the policy CMP0069 is not enabled. The following warning is generated:
```
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at third_party/glbinding/source/glbinding/CMakeLists.txt:167 (add_library):
  Policy CMP0069 is not set: INTERPROCEDURAL_OPTIMIZATION is enforced when
  enabled.  Run "cmake --help-policy CMP0069" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  INTERPROCEDURAL_OPTIMIZATION property will be ignored for target
  'glbinding'.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at third_party/glbinding/source/glbinding-aux/CMakeLists.txt:131 (add_library):
  Policy CMP0069 is not set: INTERPROCEDURAL_OPTIMIZATION is enforced when
  enabled.  Run "cmake --help-policy CMP0069" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  INTERPROCEDURAL_OPTIMIZATION property will be ignored for target
  'glbinding-aux'.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

When I force enable the policy I see a very significant gain in binary size. Without LTO on glbinding my binary weights in at 3.4MB, but with LTO it got down to 1.7MB (both sizes are after stripping). So enabling the policy allows for massive gain in binary size, assuming the user enables LTO.

**Comment by cgcostume** [comment]
@tuankiet65 thanks a lot for reporting. Can you please check if the changes of commit 9c3ec28 addresses your issue. Thanks.

**Comment by tuankiet65** [comment]
Sorry for the late reply, everything looks good on my side.
