### ISSUE TITLE
Missing glbinding.h on Ubuntu 20.04

### ISSUE THREAD

**Issue by xubury** [cginternals/glbinding#317]
Hi, I am using glbinding on Windows(MinGW-GCC) for a while. Recently, I try it on Ubuntu but fail to locate glbinding.h. Is there something wrong with the apt packge on Ubuntu? Should I just build from source?

**Comment by v1993** [comment]
Default Ubuntu repository only have very outdated glbinding package. Check out README file for PPA with recent packages.

In case you didn't know: you need '-dev' suffixed packages to get header files for compilation.
