### ISSUE TITLE
Add Ubuntu 20.10 build for PPA

### ISSUE THREAD

**Issue by v1993** [cginternals/glbinding#318]
Ubuntu 20.10 have been released, so it appears reasonable to build packages for it as well. As for right now, 20.04 package installs successfully, not tested library loading and compilation, however.

Additionally, since some adjustments were made since previous release and about 1.5 years have passed, so it might be a good idea to make another glbinding release.

**Comment by scheibel** [comment]
Thanks for your suggestions and keeping glbinding on track.
I'll add the Ubuntu 20.20 release to the PPA. I suppose you refer to the PPA at https://launchpad.net/~cginternals/+archive/ubuntu/ppa.
Regarding a new release: we're actually willing to release a new minor version of glbinding. However, we currently lack the time for thorough testing before the release.

**Comment by scheibel** [comment]
I built packages for both Ubuntu 20.10 and 21.04. However, I couldn't test them.

I'll close this issue nonetheless.
