### ISSUE TITLE
libglbinding-dbg conflicts with libglbinding-dev

### ISSUE THREAD

**Issue by v1993** [cginternals/glbinding#329]
Trying to install libglbinding-dbg from official PPA results in the following error:

```
E: /var/cache/apt/archives/libglbinding-dbg_3.3.0+579~ubuntu22.04.1_amd64.deb: trying to overwrite '/usr/share/glbinding/cmake/FindKHR.cmake', which is also in package libglbinding-dev 3.3.0+579~ubuntu22.04.1
```

The fix is most likely to exclude `/usr/share/glbinding/cmake/FindKHR.cmake` from `libglbinding-dbg` package.

**Comment by scheibel** [comment]
Thanks for reporting. I can also confirm this for our own PPA packages.
I'll provide a fix.
