### ISSUE TITLE
No Github Release for new updates?

### ISSUE THREAD

**Issue by quyykk** [cginternals/glbinding#332]
Is there a reason why there has been no Github release for the versions past 3.1.0? The current version seems to be 3.3.0.

https://github.com/cginternals/glbinding/blob/da4d2af21d3c58293a78f9e64843807892c939be/CMakeLists.txt#L70-L72

Thanks!

**Comment by scheibel** [comment]
You're right, it seems like we can and should officially release the latest improvements within our branches `v3.2` and `v3.3`.
What is holding us back is the lack of time to test these two development branches in all environments and prepare the documents and artifacts for those releases.

I test and use the current `master` branch on a regular basis on my Ubuntu 20.04, but there are a lot more environments we want to provide for.
I'm not sure if we can take the lack of new issues regarding usage errors on specific platforms (besides FreeBSD, which seems to become a new supported platform in the near future) to support our gut feelings and release any way.

However, you can already use the `v3.3` branch and treat this as a release candidate.
Is an official release here on Github an important step we should consider, soon?

**Comment by quyykk** [comment]
>  Is an official release here on Github an important step we should consider, soon?

I stumbled upon this project in search of an alternative for glew, and I wanted to check if vcpkg/conan have this library and they did, but v3.1 from 2019. I'm not sure if they would accept an update without an official Github release, but tbh I don't know. So at least for people who like to use package managers (like me) or download the library from their distros (the Arch Linux package is still on 3.1 as well), it would be useful to publish a release I'd think. 

> I'm not sure if we can take the lack of new issues regarding usage errors on specific platforms (besides FreeBSD, which seems to become a new supported platform in the near future) to support our gut feelings and release anyway.

Well, if you need another data point: v3.1 works on my Arch Linux machine on X11 and Wayland without any problems, using a recent integrated Intel GPU.

**Comment by chenrui333** [comment]
Like @quyykk said, the releases are important for package managers, not just for the project itself, but for the ecosystem at large.

**Comment by scheibel** [comment]
Thanks for the patience.
I just released [v3.3.0](https://github.com/cginternals/glbinding/releases/tag/v3.3.0).
