### ISSUE TITLE
Convert classes with no members

### ISSUE THREAD

**Issue by scheibel** [cginternals/glbinding#77]
glbinding contains several classes without members, so why not transforming it to a namespace?

Currently found classes:
 * Binding
 * Meta
 * ContextInfo

**Comment by cgcostume** [comment]
:rage: - probably a question of faith ... i'll not agree until brainwashed

**Comment by cgcostume** [comment]
actually, i was open for discussion :smile:

**Comment by scheibel** [comment]
was?

**Comment by scheibel** [comment]
This issue is now covering #78, too.

**Comment by Ryp** [comment]
I strongly agree with @scheibel, OOP should be a tool, not a religion :smile:

**Comment by sbusch42** [comment]
Yet, demanding this has to be changed into namespaces, which isn't any better, just different, seem very much like religion to me. Maybe, just maybe, we could focus on issues that really make a difference?

**Comment by scheibel** [comment]
My motivations behind this change-request (sorted by relevance):
 * Use of the most simple implementation to a given problem (and my opinion is, that classes are more complex than namespaces)
 * Shorter, clear communication of intended use
 * Reduced complexity of source code
 * Implement widely agreed coding conventions
 * Improve compilation for compilers
 * Ability to write the *namespace* in lowercase

And to sum it up: every point besides the last one is not religion but straight-forward software engineering.

But maybe a solution is to convert these non-instantiatable classes into classes that actually needs to be instantiated.
If glbinding supports different contexts, maybe we want to provide information to all of them (not just the current active one), making it required that multiple instances of ```ContextInfo``` can exist.
The same applies to ```Binding```, which will then be instantiable or even refactored and renamed to better fit the a purpose.
For ```Meta``` I'm not sure but we may find an actual requirement for the need of instances of ```Meta```.

I really do think this issue is important as such subtle "code smells" can indicate a bigger design flaw in the overall architecture and its maintainability, flexibility and robustness.
Further, this project is intended to be really public (as it is our goal with globjects, libzeug and gloperate some time in the future) and as I recently learned, imperfect presentation has impact even on loosely related topics and projects. So my goal is to provide bullet-proof software engineering.
